import{requireDb}from"./supabase.js";

const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const fmt=value=>value?new Intl.DateTimeFormat("ja-JP",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"-";
let tab="master",search="";

export async function isAdmin(){const{data,error}=await requireDb().rpc("is_admin");if(error)throw error;return Boolean(data);}
async function rows(){const db=requireDb();if(tab==="master"){const all=[];for(let offset=0;;offset+=500){const{data,error}=await db.rpc("admin_list_songs",{p_search:search,p_offset:offset,p_limit:500});if(error)throw error;all.push(...(data||[]));if(!data||data.length<500)break;}return all;}if(tab==="versions"){const{data,error}=await db.from("game_versions").select("*").order("sort_order");if(error)throw error;return data||[];}if(tab==="users"){const{data,error}=await db.rpc("admin_list_users",{p_search:search});if(error)throw error;return data||[];}const table=tab==="requests"?"song_requests":"feedback_reports";let query=db.from(table).select("*").order("created_at",{ascending:false}).limit(300);if(search)query=query.or(tab==="requests"?`title.ilike.%${search}%,artist.ilike.%${search}%,genre.ilike.%${search}%`:`message.ilike.%${search}%`);const{data,error}=await query;if(error)throw error;return data||[];}
function masterView(list){return `<div class="admin-summary">${list[0]?.total_count??0}譜面</div>${list.map(x=>`<article class="admin-card"><div class="admin-card-main">${x.banner_url?`<img src="${escapeHtml(x.banner_url)}" alt="">`:""}<div><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.genre)} / ${escapeHtml(x.artist)}</small><small>${x.chart} Lv.${x.level}${x.version_name?` / ${escapeHtml(x.version_name)}`:""}</small></div></div><button data-edit-song='${escapeHtml(JSON.stringify(x))}' class="sub-button">編集</button></article>`).join("")||'<div class="empty">該当する曲がありません。</div>'}`;}
function versionsView(list){return list.map(x=>`<article class="admin-card"><div><strong>${escapeHtml(x.name)}</strong><small>並び順 ${x.sort_order} / ${x.is_current?"現行":"過去"} / ${x.is_active?"有効":"無効"}</small></div><button data-edit-version='${escapeHtml(JSON.stringify(x))}' class="sub-button">編集</button></article>`).join("")||'<div class="empty">バージョンがありません。</div>';}
function usersView(list){return list.map(x=>`<article class="admin-card"><div><strong>${escapeHtml(x.username)}</strong><small>登録 ${x.registered_count}譜面 / 平均 ${Number(x.average_score||0).toLocaleString()}</small><small>登録日 ${fmt(x.created_at)}</small></div></article>`).join("")||'<div class="empty">ユーザーがいません。</div>';}
function requestView(list){return list.map(x=>`<article class="admin-card"><div><strong>${escapeHtml(x.title)} / ${x.chart} Lv.${x.level}</strong><small>${escapeHtml(x.genre)} / ${escapeHtml(x.artist)}</small><small>${escapeHtml(x.note||"")} · ${fmt(x.created_at)}</small></div><div class="admin-actions"><button data-status-table="song_requests" data-status-id="${x.id}" data-status="approved">承認</button><button data-status-table="song_requests" data-status-id="${x.id}" data-status="rejected">却下</button><b class="status ${x.status}">${x.status}</b></div></article>`).join("")||'<div class="empty">登録依頼はありません。</div>';}
function feedbackView(list){return list.map(x=>`<article class="admin-card"><div><strong>${x.category==="bug"?"不具合":"要望"}</strong><p>${escapeHtml(x.message)}</p><small>${fmt(x.created_at)}</small>${x.admin_reply?`<p class="admin-reply">返信：${escapeHtml(x.admin_reply)}</p>`:""}</div><div class="admin-actions"><button data-reply-id="${x.id}">返信</button><button data-status-table="feedback_reports" data-status-id="${x.id}" data-status="resolved">解決済み</button><b class="status ${x.status}">${x.status}</b></div></article>`).join("")||'<div class="empty">報告はありません。</div>';}
export async function renderAdmin(){const target=document.querySelector("#adminContent");target.innerHTML='<div class="empty">読み込み中…</div>';try{const list=await rows();target.innerHTML=tab==="master"?masterView(list):tab==="versions"?versionsView(list):tab==="users"?usersView(list):tab==="requests"?requestView(list):feedbackView(list);}catch(error){target.innerHTML=`<p class="error">${escapeHtml(error.message||error)}</p>`;}}
export function setAdminTab(value){tab=value;document.querySelectorAll("[data-admin-tab]").forEach(b=>b.classList.toggle("active",b.dataset.adminTab===tab));document.querySelector("#adminAddButton").hidden=!['master','versions'].includes(tab);return renderAdmin();}
export function setAdminSearch(value){search=value.trim();return renderAdmin();}
export function currentAdminTab(){return tab;}
export async function updateStatus(table,id,status,adminReply){const patch={status};if(table==="feedback_reports"&&adminReply!==undefined)patch.admin_reply=adminReply;const{error}=await requireDb().from(table).update(patch).eq("id",id);if(error)throw error;}
export async function saveVersion(values,id){const payload={name:values.name.trim(),slug:values.slug.trim(),sort_order:Number(values.sort_order),is_current:values.is_current,is_active:values.is_active};const db=requireDb(),result=id?await db.from("game_versions").update(payload).eq("id",id):await db.from("game_versions").insert(payload);if(result.error)throw result.error;}
export async function saveSong(values,id){const payload={master_key:values.master_key.trim(),genre:values.genre.trim(),title:values.title.trim(),artist:values.artist.trim(),chart:values.chart,level:Number(values.level),banner_url:values.banner_url.trim(),version_id:values.version_id||null};const db=requireDb(),result=id?await db.from("songs").update(payload).eq("id",id):await db.from("songs").insert(payload);if(result.error)throw result.error;}
export async function loadVersions(){const{data,error}=await requireDb().from("game_versions").select("id,name").eq("is_active",true).order("sort_order");if(error)throw error;return data||[];}
