import{requireDb}from"./supabase.js";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),fmt=v=>v?new Date(v).toLocaleString("ja-JP"):"-",PAGE_SIZE=50;let tab="master",search="",page=1,masterLevel="ALL",masterVersion="ALL",masterChart="ALL";
export async function isAdmin(){const{data,error}=await requireDb().rpc("is_admin");if(error)throw error;return!!data;}
async function rows(){const db=requireDb();if(tab==="master"){const all=[];for(let from=0;;from+=500){let q=db.from("songs").select("*,game_versions(name)").order("title").range(from,from+499);if(search)q=q.or(`title.ilike.%${search}%,genre.ilike.%${search}%,artist.ilike.%${search}%`);const{data,error}=await q;if(error)throw error;all.push(...data);if(data.length<500)break;}return all.filter(x=>(masterVersion==="ALL"||x.version_id===masterVersion)&&(masterChart==="ALL"||x[masterChart.toLowerCase()+"_level"]!=null)&&(masterLevel==="ALL"||["LIGHT","NORMAL","HYPER","EX"].some(chart=>(masterChart==="ALL"||masterChart===chart)&&Number(x[chart.toLowerCase()+"_level"])===Number(masterLevel))));}if(tab==="versions"){const{data,error}=await db.from("game_versions").select("*").order("sort_order");if(error)throw error;return data||[];}if(tab==="users"){const{data,error}=await db.rpc("admin_list_users",{p_search:search});if(error)throw error;return data||[];}if(tab==="requests"){await db.rpc("merge_song_requests_into_master");}const table=tab==="requests"?"song_requests":"feedback_reports";let q=db.from(table).select("*").order("created_at",{ascending:false}).limit(500);if(tab==="requests")q=q.eq("status","pending");if(tab==="feedback")q=q.neq("message","");if(search)q=q.ilike(tab==="requests"?"title":"message",`%${search}%`);const{data,error}=await q;if(error)throw error;return(data||[]).filter(x=>tab!=="feedback"||String(x.message||"").trim());}
const levels=x=>["LIGHT","NORMAL","HYPER","EX"].map(c=>`${c} ${x[c.toLowerCase()+"_level"]??"-"}`).join(" / ");
function pager(total){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));page=Math.min(page,pages);if(pages<=1)return"";const options=Array.from({length:pages},(_,i)=>`<option value="${i+1}" ${i+1===page?"selected":""}>${i+1} / ${pages}</option>`).join("");return `<nav class="score-pager"><span>${total.toLocaleString("ja-JP")}件</span><div class="pager-controls"><button type="button" data-admin-page="${page-1}" ${page===1?"disabled":""}>◀</button><label class="pager-select"><select data-admin-page-select>${options}</select></label><button type="button" data-admin-page="${page+1}" ${page===pages?"disabled":""}>▶</button></div></nav>`;}
function view(all){const list=all.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);let html;if(tab==="master")html=list.map(x=>`<article class="admin-card"><div class="admin-card-main">${x.banner_url?`<img src="${esc(x.banner_url)}" alt="">`:""}<div><strong>${esc(x.title)}</strong><small>${esc(x.genre)} / ${esc(x.artist)}</small><small>登場バージョン：${esc(x.game_versions?.name||"未設定")}</small><small>${levels(x)}</small></div></div><button class="sub-button" data-edit-song="${encodeURIComponent(JSON.stringify(x))}">編集</button></article>`).join("");else if(tab==="versions")html=list.map(x=>`<article class="admin-card"><div><strong>${esc(x.name)}</strong><small>並び順 ${x.sort_order} / ${x.is_current?"現行":"過去"} / ${x.is_active?"有効":"無効"}</small></div><button class="sub-button" data-edit-version="${encodeURIComponent(JSON.stringify(x))}">編集</button></article>`).join("");else if(tab==="users")html=list.map(x=>`<article class="admin-card"><div><strong>${esc(x.username)}</strong><small>登録 ${x.registered_count}譜面 / 平均 ${x.average_score||0}</small><small>${fmt(x.created_at)}</small></div><button class="danger-button" data-delete-user="${x.user_id}" data-user-name="${encodeURIComponent(x.username)}">削除</button></article>`).join("");else if(tab==="requests")html=list.map(x=>{const valid=["LIGHT","NORMAL","HYPER","EX"].includes(x.chart)&&Number(x.level)>=1&&Number(x.level)<=50;return`<article class="admin-card request-card"><div><small class="request-kind">新規曲として登録</small><small class="field-label">曲名</small><strong>${esc(x.title)}</strong><div class="request-chart"><span><small>譜面</small>${esc(x.chart||"未設定")}</span><span><small>レベル</small>${valid?`Lv.${x.level}`:"未設定"}</span></div><small class="field-label">ジャンル／アーティスト</small><p>${esc(x.genre)}<br>${esc(x.artist)}</p></div><div class="admin-actions"><button data-approve-request="${x.id}" ${valid?"":"disabled"}>承認</button><button data-status-table="song_requests" data-status-id="${x.id}" data-status="rejected">却下</button></div></article>`;}).join("");else html=list.map(x=>`<article class="admin-card"><div><strong>${x.category==="bug"?"不具合":"要望"}</strong><p>${esc(x.message)}</p><small>${fmt(x.created_at)}</small></div><div class="admin-actions"><button data-reply-id="${x.id}">返信</button><button data-status-table="feedback_reports" data-status-id="${x.id}" data-status="resolved">解決済み</button></div></article>`).join("");return html+pager(all.length);}
export async function renderAdmin(){const el=document.querySelector("#adminContent");el.innerHTML='<div class="empty">読み込み中…</div>';try{const list=await rows();el.innerHTML=view(list)||'<div class="empty">データがありません。</div>';}catch(e){el.innerHTML=`<p class="error">${esc(e.message||e)}</p>`;}}
export function setAdminTab(v){tab=v;page=1;document.querySelectorAll("[data-admin-tab]").forEach(b=>b.classList.toggle("active",b.dataset.adminTab===v));document.querySelector("#adminAddButton").hidden=!["master","versions"].includes(v);document.querySelector("#adminMasterFilters").hidden=v!=="master";return renderAdmin();}export function setAdminSearch(v){search=v.trim();page=1;return renderAdmin();}export function setAdminMasterFilters({level,version,chart}){masterLevel=level;masterVersion=version;masterChart=chart;page=1;return renderAdmin();}export function setAdminPage(v){page=Math.max(1,Number(v)||1);return renderAdmin();}export function currentAdminTab(){return tab;}
export async function updateStatus(table,id,status,adminReply){const data={status};if(adminReply!==undefined)data.admin_reply=adminReply;const{error}=await requireDb().from(table).update(data).eq("id",id);if(error)throw error;}
export async function approveSongRequest(id){const{error}=await requireDb().rpc("approve_song_request_v2",{p_request_id:id});if(error)throw error;}
export async function saveVersion(v,id){const data={name:v.name.trim(),slug:v.slug.trim(),sort_order:Number(v.sort_order),is_current:v.is_current,is_active:v.is_active},db=requireDb(),r=id?await db.from("game_versions").update(data).eq("id",id):await db.from("game_versions").insert(data);if(r.error)throw r.error;}
export async function saveSong(v,id){const n=x=>x?Number(x):null,data={master_key:v.master_key.trim(),genre:v.genre.trim(),title:v.title.trim(),artist:v.artist.trim(),banner_url:v.banner_url.trim(),light_level:n(v.light_level),normal_level:n(v.normal_level),hyper_level:n(v.hyper_level),ex_level:n(v.ex_level),version_id:v.version_id||null},db=requireDb(),r=id?await db.from("songs").update(data).eq("id",id):await db.from("songs").insert(data);if(r.error)throw r.error;}
export async function uploadSongBanner(file){if(!file?.size)return"";if(!["image/png","image/jpeg","image/webp","image/gif"].includes(file.type))throw new Error("PNG・JPEG・WebP・GIF画像を選択してください。");if(file.size>2*1024*1024)throw new Error("バナー画像は2MB以下にしてください。");const ext={"image/png":"png","image/jpeg":"jpg","image/webp":"webp","image/gif":"gif"}[file.type],path=`songs/${crypto.randomUUID()}.${ext}`,db=requireDb(),{error}=await db.storage.from("song-banners").upload(path,file,{cacheControl:"31536000",contentType:file.type,upsert:false});if(error)throw error;return db.storage.from("song-banners").getPublicUrl(path).data.publicUrl;}
export async function loadVersions(){const{data,error}=await requireDb().from("game_versions").select("id,name").eq("is_active",true).order("sort_order");if(error)throw error;return data||[];}
export async function deleteUser(userId){const{error}=await requireDb().rpc("admin_delete_user",{p_user_id:userId});if(error)throw error;}
