import{isConfigured}from"./supabase.js";
import{changePassword,changeUsername,currentUser,currentUsername,loadMyProfile,login,logout,onAuthChange,register,savePoptomo}from"./auth.js";
import{downloadSongMaster,importSongMaster}from"./songs.js";
import{loadScoreCatalog,rankFromScore,saveScore,syncScores}from"./scores.js";
import{loadUsers}from"./users.js";
import{filterScores,MEDALS,medalInfo,renderScores,renderStats,renderUsers,setTheme,showTab}from"./ui.js";
import{submitFeedback,submitSongRequest}from"./requests.js";
import{approveSongRequest,currentAdminTab,deleteUser,isAdmin,loadVersions,renderAdmin,saveSong,saveVersion,setAdminPage,setAdminSearch,setAdminTab,updateStatus,uploadSongBanner}from"./admin.js";

let scores=[],scorePage=1,userRows=[],userPage=1,authMode="login",selectedSong=null,editingScoreId=null,admin=false,adminEdit=null;
const $=selector=>document.querySelector(selector);
const attr=value=>String(value??"").replace(/[&<>"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
const wait=(fn,delay=250)=>{let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),delay);};};
function setHistoryInput(row){const input=$("#manualHistoryScore"),stored=Math.max(Number(row?.official_score)||0,Number(row?.manual_history_score)||0),display=Math.max(stored,Number(row?.version_score)||0);input.value=display||"";input.dataset.stored=String(stored);input.dataset.display=String(display);}
function historyValueForSave(){const input=$("#manualHistoryScore"),entered=Math.max(0,Number(input.value)||0),stored=Math.max(0,Number(input.dataset.stored)||0),display=Math.max(0,Number(input.dataset.display)||0);return display>stored&&entered===display?stored:entered;}

function populateVersionFilter(){const select=$("#versionFilter"),current=select.value,versions=[...new Map(scores.map(x=>[x.version_name,{name:x.version_name,order:x.version_order}])).values()].sort((a,b)=>a.order-b.order||a.name.localeCompare(b.name,"ja"));select.innerHTML='<option value="ALL">全バージョン</option>'+versions.map(x=>`<option value="${attr(x.name)}">${attr(x.name)}</option>`).join("");select.value=[...select.options].some(x=>x.value===current)?current:"ALL";}
async function refreshAuth(){const user=await currentUser();$("#playerName").textContent=user?await currentUsername(user):"GUEST";$("#authButton").hidden=Boolean(user);$("#logoutButton").hidden=!user;admin=user?await isAdmin().catch(()=>false):false;$("#adminTabButton").hidden=!admin;document.querySelectorAll(".admin-only").forEach(x=>x.hidden=!admin);document.querySelector(".tabs").classList.toggle("has-admin",admin);scores=isConfigured?await loadScoreCatalog(user?.id):[];populateVersionFilter();applyFilters(true);}
function applyFilters(reset=false){if(reset)scorePage=1;const filtered=filterScores(scores);scorePage=renderScores(filtered,scorePage);renderStats(filtered);}
function toggleTheme(){setTheme(document.documentElement.dataset.theme==="dark"?"light":"dark");}
function populateLevels(){const selects=[$("#levelFilter"),$("#defaultLevelFilter")];for(let level=50;level>=1;level--){for(const select of selects){const option=document.createElement("option");option.value=String(level);option.textContent=`Lv.${level}`;select.append(option);}}const saved=localStorage.getItem("popn-default-level")||"ALL";for(const select of selects)select.value=[...select.options].some(x=>x.value===saved)?saved:"ALL";}
async function importHash(){const marker="#popn-sync-gzip=";if(!location.hash.startsWith(marker))return;try{const binary=atob(decodeURIComponent(location.hash.slice(marker.length))),bytes=Uint8Array.from(binary,char=>char.charCodeAt(0)),text=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"))).text(),payload=JSON.parse(text);if(payload.type!=="POPN_SCORE_SYNC"||!Array.isArray(payload.records))throw new Error("同期データが不正です。");const result=await syncScores(payload.records);history.replaceState(null,"",location.pathname+location.search);alert(`${result.saved}譜面を保存しました。曲マスター未登録：${result.unmatched}譜面`);await refreshAuth();}catch(error){alert(`同期に失敗しました：${error.message||error}`);}}

populateLevels();setTheme(localStorage.getItem("popn-theme")==="dark"?"dark":"light");$("#setupNotice").hidden=isConfigured;
let lockedScroll=0;function syncDialogLock(){const open=Boolean(document.querySelector("dialog[open]")),locked=document.body.classList.contains("modal-open");if(open&&!locked){lockedScroll=window.scrollY;document.body.classList.add("modal-open");document.body.style.top=`-${lockedScroll}px`;}else if(!open&&locked){document.body.classList.remove("modal-open");document.body.style.top="";window.scrollTo(0,lockedScroll);}}for(const dialog of document.querySelectorAll("dialog")){dialog.addEventListener("close",()=>queueMicrotask(syncDialogLock));new MutationObserver(syncDialogLock).observe(dialog,{attributes:true,attributeFilter:["open"]});}for(const button of document.querySelectorAll("[data-dialog-close]"))button.addEventListener("click",()=>button.closest("dialog").close());
function showNotice(message){const dialog=$("#noticeDialog");$("#noticeMessage").textContent=String(message??"");if(dialog.open)dialog.close();dialog.showModal();}window.alert=showNotice;
function askConfirm(message){const dialog=$("#confirmDialog");$("#confirmMessage").textContent=String(message??"");return new Promise(resolve=>{dialog.addEventListener("close",()=>resolve(dialog.returnValue==="ok"),{once:true});dialog.showModal();});}
function askText(message){const dialog=$("#promptDialog"),input=$("#promptInput");$("#promptLabel").textContent=String(message??"");input.value="";return new Promise(resolve=>{dialog.addEventListener("close",()=>resolve(dialog.returnValue==="ok"?input.value:null),{once:true});dialog.showModal();queueMicrotask(()=>input.focus());});}
$("#menuButton").addEventListener("click",()=>$("#menuDialog").showModal());$("#settingsThemeButton").addEventListener("click",toggleTheme);
$("#defaultLevelFilter").addEventListener("change",event=>{const value=event.target.value;localStorage.setItem("popn-default-level",value);$("#levelFilter").value=value;applyFilters(true);});
async function refreshUsers(reset=false){if(reset)userPage=1;userRows=await loadUsers($("#userSearchInput").value);userPage=renderUsers(userRows,userPage);}
for(const button of document.querySelectorAll(".tabs button"))button.addEventListener("click",async()=>{if(button.dataset.tab==="admin"&&!admin)return;showTab(button.dataset.tab);if(button.dataset.tab==="admin")await renderAdmin();if(button.dataset.tab==="users"&&isConfigured){try{await refreshUsers(false);}catch(error){alert(error.message||error);}}});
for(const selector of["#searchInput","#levelFilter","#versionFilter","#medalFilter"])$(selector).addEventListener(selector==="#searchInput"?"input":"change",()=>applyFilters(true));
$("#reloadButton").addEventListener("click",event=>{event.currentTarget.classList.add("is-loading");location.reload();});
$("#authButton").addEventListener("click",()=>$("#authDialog").showModal());$("#logoutButton").addEventListener("click",async()=>{await logout();await refreshAuth();});
$("#authModeButton").addEventListener("click",()=>{authMode=authMode==="login"?"register":"login";$("#authTitle").textContent=authMode==="login"?"ログイン":"新規登録";$("#authModeButton").textContent=authMode==="login"?"新規登録へ":"ログインへ";$("#authForm button[type=submit]").textContent=authMode==="login"?"ログイン":"登録";});
$("#authForm").addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{if(authMode==="login")await login(form.get("username"),form.get("password"));else await register(form.get("username"),form.get("password"));$("#authDialog").close();await refreshAuth();}catch(error){$("#authError").textContent=error.message||error;}});
$("#manualButton").addEventListener("click",async()=>{if(!await currentUser()){alert("追加依頼を送るにはログインしてください。");return;}$("#songRequestForm").reset();$("#songRequestDialog .error").textContent="";$("#songRequestDialog").showModal();});$("#syncHelpButton").addEventListener("click",()=>{$("#menuDialog").close();$("#syncDialog").showModal();});
function updateRankPreview(score){const value=rankFromScore(score),slug=value.replace("+","plus").toLowerCase(),el=$("#manualRank");el.className=`rank-text rank-${slug}`;el.textContent=value;el.setAttribute("aria-label",value);el.title=value;}$("#manualScoreInput").addEventListener("input",event=>updateRankPreview(event.target.value));
$("#manualForm").addEventListener("submit",async event=>{event.preventDefault();if(!selectedSong){$("#manualError").textContent="曲マスターから譜面を選択してください。";return;}const formElement=event.currentTarget,form=new FormData(formElement);try{await saveScore(selectedSong.song_id||selectedSong.id,selectedSong.chart,historyValueForSave(),form.get("version_score"),form.get("medal_code"));$("#manualDialog").close();formElement.reset();updateRankPreview(0);selectedSong=null;editingScoreId=null;await refreshAuth();}catch(error){$("#manualError").textContent=error.message||error;}});
$("#scoreList").addEventListener("click",async event=>{const pager=event.target.closest("[data-score-page]");if(pager&&!pager.disabled){scorePage=Number(pager.dataset.scorePage);applyFilters(false);$("#scoreList").scrollIntoView({behavior:"smooth",block:"start"});return;}const button=event.target.closest("[data-edit-score]");if(!button)return;if(!await currentUser()){alert("スコアを登録するにはログインしてください。");return;}const row=scores.find(x=>x.id===button.dataset.editScore);if(!row)return;editingScoreId=row.id;selectedSong=row;$("#songGenreInput").value=row.genre;$("#songTitleInput").value=`${row.title} / ${row.chart} ${row.level}`;$("#manualArtist").textContent=`アーティスト：${row.artist}`;$("#manualArtist").hidden=false;$("#manualVersion").textContent=`登場バージョン：${row.version_name||"未設定"}`;$("#manualVersion").hidden=false;$("#songGenreInput").disabled=true;$("#songTitleInput").disabled=true;setHistoryInput(row);$("#historyScoreGuide").textContent="今作スコアが上回る場合は同じ値を表示します";$("#manualScoreInput").value=row.version_score||0;chooseMedal(row.medal_code);updateRankPreview(row.version_score||0);$("#manualError").textContent="";$("#manualDialog h2").textContent="登録スコアを編集";$("#manualDialog").showModal();});
$("#scoreList").addEventListener("change",event=>{if(event.target.matches("[data-score-page-select]")){scorePage=Number(event.target.value);applyFilters(false);$("#scoreList").scrollIntoView({behavior:"smooth",block:"start"});}});
$("#masterFileInput").addEventListener("change",async event=>{const file=event.target.files?.[0];if(!file)return;try{const count=await importSongMaster(file);await refreshAuth();if(currentAdminTab()==="master")await renderAdmin();alert(`${count}曲を曲マスターへ登録・更新しました。`);}catch(error){alert(`曲マスター投入に失敗しました：${error.message||error}`);}finally{event.target.value="";}});
$("#masterDownloadButton").addEventListener("click",async()=>{try{const count=await downloadSongMaster();alert(`${count}曲の曲マスターをダウンロードしました。`);}catch(error){alert(`曲マスターのダウンロードに失敗しました：${error.message||error}`);}});
$("#userSearchInput").addEventListener("input",wait(()=>refreshUsers(true).catch(console.error),350));$("#userList").addEventListener("click",event=>{const button=event.target.closest("[data-user-page]");if(button&&!button.disabled){userPage=Number(button.dataset.userPage);renderUsers(userRows,userPage);}});$("#userList").addEventListener("change",event=>{if(event.target.matches("[data-user-page-select]")){userPage=Number(event.target.value);renderUsers(userRows,userPage);}});
$("#feedbackButton").addEventListener("click",()=>{$("#menuDialog").close();$("#feedbackDialog").showModal();});
$("#songRequestForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,errorBox=form.querySelector(".error"),values=Object.fromEntries(new FormData(form)),charts=[["LIGHT","light_level"],["NORMAL","normal_level"],["HYPER","hyper_level"],["EX","ex_level"]].filter(([,key])=>String(values[key]||"").trim());if(!charts.length){errorBox.textContent="少なくとも1つの譜面レベルを入力してください。";return;}errorBox.textContent="";try{const results=[];for(const[chart,key]of charts)results.push(await submitSongRequest({...values,chart,level:values[key]}));form.reset();$("#songRequestDialog").close();alert(results.every(result=>result==="merged")?"既存の曲マスターに統合しました。":"登録依頼を送信しました。");}catch(error){errorBox.textContent=error.message||error;}});
$("#feedbackForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,errorBox=event.currentTarget.querySelector(".error");try{await submitFeedback(Object.fromEntries(new FormData(form)));form.reset();$("#feedbackDialog").close();alert("送信しました。");}catch(error){errorBox.textContent=error.message||error;}});
function chooseMedal(code){const info=medalInfo(code),input=$("#manualForm [name=medal_code]"),button=$("#medalPickerButton"),image=button.querySelector("img"),label=button.querySelector("span");input.value=code;image.src=info.url;image.hidden=!info.url;label.textContent=info.url?"":code==="none"?"－":info.label;label.hidden=Boolean(info.url);button.title=info.label;button.setAttribute("aria-label",info.label);$("#medalPicker").hidden=true;}
$("#medalPicker").innerHTML=MEDALS.map(([code,label,file])=>`<button type="button" data-medal="${code}">${file?`<img src="https://eacache.s.konaminet.jp/game/popn/popn29/images/p/howto/more/${file}" alt="">`:""}<span>${label}</span></button>`).join("");
$("#medalPickerButton").addEventListener("click",()=>{$("#medalPicker").hidden=!$("#medalPicker").hidden;});
$("#medalPicker").addEventListener("click",event=>{const button=event.target.closest("[data-medal]");if(button)chooseMedal(button.dataset.medal);});chooseMedal("none");
const filterMedals=[["ALL","すべて",""],...MEDALS];$("#filterMedalPicker").innerHTML=filterMedals.map(([code,label,file])=>`<button type="button" data-filter-medal="${code}">${code==="ALL"?`<span class="filter-medal-all">すべて</span>`:file?`<img src="https://eacache.s.konaminet.jp/game/popn/popn29/images/p/howto/more/${file}" alt=""><span>${label}</span>`:`<span class="filter-medal-empty">－</span><span>${label.replace(/^－\s*/,"")}</span>`}</button>`).join("");$("#filterMedalButton").addEventListener("click",()=>{$("#filterMedalPicker").hidden=!$("#filterMedalPicker").hidden;});$("#filterMedalPicker").addEventListener("click",event=>{const button=event.target.closest("[data-filter-medal]");if(!button)return;$("#medalFilter").value=button.dataset.filterMedal;$("#filterMedalButton span").textContent=button.dataset.filterMedal==="none"?"－ 未プレー":button.querySelector("span:last-child").textContent;$("#filterMedalPicker").hidden=true;$("#medalFilter").dispatchEvent(new Event("change"));});
async function copyTool(file){const response=await fetch(`./tools/${file}`,{cache:"no-store"});if(!response.ok)throw new Error("コードを読み込めませんでした。");const text=await response.text();try{await navigator.clipboard.writeText(text);}catch{const area=document.createElement("textarea");area.value=text;area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();if(!document.execCommand("copy"))throw new Error("コピーできませんでした。");area.remove();}return file.includes("score-sync")?"同期用コードをコピーしました。ブックマークのURL欄へ貼り付けてください。":"抽出コードをコピーしました。公式サイトのConsoleへ貼り付けてください。";}
$("#copySyncButton").addEventListener("click",async()=>{const status=$(".sync-status");try{await copyTool("popn-score-sync.txt");status.textContent="コードをコピーしました";}catch(error){status.textContent=`コピー失敗：${error.message||error}`;}});
$("#myPageButton").addEventListener("click",async()=>{const user=await currentUser();if(!user){alert("マイページを利用するにはログインしてください。");return;}const profile=await loadMyProfile();$("#newUsernameInput").value=profile.username;$("#poptomoIdInput").value=profile.poptomo_id||"";$("#poptomoPublicInput").checked=Boolean(profile.poptomo_public);$("#menuDialog").close();$("#myPageDialog").showModal();});
$("#poptomoForm").addEventListener("submit",async event=>{event.preventDefault();const errorBox=event.currentTarget.querySelector(".error");try{await savePoptomo($("#poptomoIdInput").value,$("#poptomoPublicInput").checked);errorBox.textContent="";alert("ポプとも設定を保存しました。");}catch(error){errorBox.textContent=error.message||error;}});
$("#usernameForm").addEventListener("submit",async event=>{event.preventDefault();const errorBox=event.currentTarget.querySelector(".error");try{const name=await changeUsername(new FormData(event.currentTarget).get("username"));$("#playerName").textContent=name;errorBox.textContent="";alert("ユーザー名を変更しました。次回から新しいユーザー名でログインしてください。");}catch(error){errorBox.textContent=error.message||error;}});
$("#passwordForm").addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget),password=String(form.get("password")||""),confirm=String(form.get("password_confirm")||""),errorBox=event.currentTarget.querySelector(".error");if(password!==confirm){errorBox.textContent="確認用パスワードが一致しません。";return;}try{await changePassword(password);event.currentTarget.reset();errorBox.textContent="";alert("パスワードを変更しました。");}catch(error){errorBox.textContent=error.message||error;}});
document.querySelector('[data-copy-tool="master"]').addEventListener("click",()=>copyTool("popn-master-extractor.txt").then(alert).catch(error=>alert(error.message||error)));
for(const button of document.querySelectorAll("[data-admin-tab]"))button.addEventListener("click",()=>setAdminTab(button.dataset.adminTab));
$("#adminSearch").addEventListener("input",wait(event=>setAdminSearch(event.target.value),300));
async function openAdminEditor(kind,item={}){adminEdit={kind,item};const fields=$("#adminEditFields");if(kind==="version"){$("#adminEditTitle").textContent=item.id?"バージョン編集":"バージョン追加";fields.innerHTML=`<label>表示名<input name="name" required value="${attr(item.name)}"></label><label>識別名<input name="slug" required pattern="[a-z0-9_-]+" value="${attr(item.slug)}"></label><label>並び順<input name="sort_order" type="number" required value="${item.sort_order??0}"></label><label class="check-row"><input name="is_current" type="checkbox" ${item.is_current?"checked":""}>現行バージョン</label><label class="check-row"><input name="is_active" type="checkbox" ${item.is_active!==false?"checked":""}>有効</label>`;}else{const versions=await loadVersions(),generated=[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,"0")).join("");$("#adminEditTitle").textContent=item.id?"曲マスター編集":"曲マスター追加";fields.innerHTML=`<label>曲ID<input name="master_key" readonly value="${attr(item.master_key||generated)}"><small>新規追加時は自動設定されます。</small></label><label>バナー画像URL（任意）<input name="banner_url" type="url" value="${attr(item.banner_url)}" placeholder="https://..."></label><label class="banner-upload">バナー画像をアップロード（任意）<input name="banner_file" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><small>画像を選ぶとURLより優先します（2MB以下）。</small></label><div class="form-grid"><label>ジャンル<input name="genre" required value="${attr(item.genre)}"></label><label>曲名<input name="title" required value="${attr(item.title)}"></label></div><label>アーティスト<input name="artist" required value="${attr(item.artist)}"></label><div class="master-levels">${[["LIGHT","light_level"],["NORMAL","normal_level"],["HYPER","hyper_level"],["EX","ex_level"]].map(([label,key])=>`<label>${label}<input name="${key}" type="number" min="1" max="50" value="${item[key]||""}" placeholder="なし"></label>`).join("")}</div><label>登場バージョン<select name="version_id"><option value="">未設定</option>${versions.map(x=>`<option value="${x.id}" ${x.id===item.version_id?"selected":""}>${attr(x.name)}</option>`).join("")}</select></label>`;}$("#adminEditDialog").showModal();}
$("#adminAddButton").addEventListener("click",()=>openAdminEditor(currentAdminTab()==="versions"?"version":"song"));
$("#adminContent").addEventListener("click",async event=>{const song=event.target.closest("[data-edit-song]"),version=event.target.closest("[data-edit-version]"),approve=event.target.closest("[data-approve-request]"),status=event.target.closest("[data-status-id]"),reply=event.target.closest("[data-reply-id]"),remove=event.target.closest("[data-delete-user]");try{if(song)await openAdminEditor("song",JSON.parse(decodeURIComponent(song.dataset.editSong)));if(version)await openAdminEditor("version",JSON.parse(decodeURIComponent(version.dataset.editVersion)));if(approve){await approveSongRequest(approve.dataset.approveRequest);await renderAdmin();alert("曲マスターへ登録・統合しました。");}if(status){await updateStatus(status.dataset.statusTable,status.dataset.statusId,status.dataset.status);await renderAdmin();}if(reply){const message=await askText("ユーザーへの返信を入力してください。");if(message!==null){await updateStatus("feedback_reports",reply.dataset.replyId,"answered",message.trim());await renderAdmin();}}if(remove&&await askConfirm(`${decodeURIComponent(remove.dataset.userName)} を削除しますか？\nスコアなど、このユーザーのデータも削除されます。`)){await deleteUser(remove.dataset.deleteUser);await renderAdmin();alert("ユーザーを削除しました。");}}catch(error){alert(error.message||error);}});
$("#adminContent").addEventListener("click",event=>{const button=event.target.closest("[data-admin-page]");if(button&&!button.disabled)setAdminPage(button.dataset.adminPage);});$("#adminContent").addEventListener("change",event=>{if(event.target.matches("[data-admin-page-select]"))setAdminPage(event.target.value);});
$("#adminEditForm").addEventListener("submit",async event=>{event.preventDefault();const raw=Object.fromEntries(new FormData(event.currentTarget)),errorBox=event.currentTarget.querySelector(".error");try{if(adminEdit.kind==="version")await saveVersion({...raw,is_current:event.currentTarget.elements.is_current.checked,is_active:event.currentTarget.elements.is_active.checked},adminEdit.item.id);else{const file=event.currentTarget.elements.banner_file?.files?.[0];if(file)raw.banner_url=await uploadSongBanner(file);await saveSong(raw,adminEdit.item.id);}$("#adminEditDialog").close();await renderAdmin();}catch(error){errorBox.textContent=error.message||error;}});
onAuthChange(refreshAuth);await refreshAuth();await importHash();
