import{isConfigured}from"./supabase.js";
import{changePassword,changeUsername,currentUser,currentUsername,loadMyProfile,login,logout,onAuthChange,register,saveDisplayPreferences,savePoptomo}from"./auth.js";
import{downloadSongMaster,importSongMaster}from"./songs.js";
import{loadScoreCatalog,rankFromScore,saveScore,songPopClass,syncScores}from"./scores.js?v=3.0.35";
import{loadUsers}from"./users.js";
import{filterScores,MEDALS,medalInfo,renderPopClass,renderScores,renderStats,renderUsers,setTheme,showTab}from"./ui.js?v=3.0.37";
import{loadFeedbackHistory,submitFeedback,submitSongRequest}from"./requests.js";
import{approveSongRequest,clearMyRegisteredScores,currentAdminTab,deleteFeedback,deleteUser,isAdmin,loadVersions,renderAdmin,saveSong,saveVersion,setAdminMasterFilters,setAdminPage,setAdminSearch,setAdminTab,updateStatus,uploadSongBanner}from"./admin.js";

let scores=[],scorePage=1,userRows=[],userPage=1,authMode="login",selectedSong=null,editingScoreId=null,admin=false,adminEdit=null,preferenceUserId=null;
const $=selector=>document.querySelector(selector);
const attr=value=>String(value??"").replace(/[&<>"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
const wait=(fn,delay=250)=>{let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),delay);};};
function setHistoryInput(row){const input=$("#manualHistoryScore"),stored=Math.max(Number(row?.official_score)||0,Number(row?.manual_history_score)||0),display=Math.max(stored,Number(row?.version_score)||0);input.value=display||"";input.dataset.stored=String(stored);input.dataset.display=String(display);}
function historyValueForSave(){const input=$("#manualHistoryScore"),entered=Math.max(0,Number(input.value)||0),stored=Math.max(0,Number(input.dataset.stored)||0),display=Math.max(0,Number(input.dataset.display)||0);return display>stored&&entered===display?stored:entered;}

function populateVersionFilter(){const select=$("#versionFilter"),current=select.value,versions=[...new Map(scores.map(x=>[x.version_name,{name:x.version_name,order:x.version_order}])).values()].sort((a,b)=>a.order-b.order||a.name.localeCompare(b.name,"ja"));select.innerHTML='<option value="ALL">全バージョン</option>'+versions.map(x=>`<option value="${attr(x.name)}">${attr(x.name)}</option>`).join("");select.value=[...select.options].some(x=>x.value===current)?current:"ALL";}
function setScoreLoading(loading){const panel=$("#scoresPanel"),loader=$("#scoreLoading"),overview=$("#scoreOverview");panel?.classList.toggle("is-score-loading",loading);if(loader)loader.hidden=!loading;if(overview&&loading)overview.hidden=true;}
async function refreshAuth(resetPage=true){const user=await currentUser();document.body.classList.remove("auth-pending","auth-guest","auth-user");document.body.classList.add(user?"auth-user":"auth-guest");$("#playerName").textContent=user?await currentUsername(user):"";$("#logoutButton").hidden=!user;if(!user){preferenceUserId=null;admin=false;scores=[];setScoreLoading(false);$("#scoreOverview").hidden=true;return;}const showLoading=!scores.length;try{if(showLoading)setScoreLoading(true);if(preferenceUserId!==user.id){const profile=await loadMyProfile();setTheme(profile.theme);const level=profile.default_level==null?"ALL":String(profile.default_level);$("#defaultLevelFilter").value=level;$("#levelFilter").value=level;preferenceUserId=user.id;}admin=await isAdmin().catch(()=>false);$("#adminTabButton").hidden=!admin;document.querySelectorAll(".admin-only").forEach(x=>x.hidden=!admin);document.querySelector(".tabs").classList.toggle("has-admin",admin);scores=isConfigured?await loadScoreCatalog(user.id):[];populateVersionFilter();if(admin)await populateAdminMasterFilters();applyFilters(resetPage);$("#scoreOverview").hidden=false;}finally{if(showLoading)setScoreLoading(false);}}
function applyFilters(reset=false){if(reset)scorePage=1;const filtered=filterScores(scores);scorePage=renderScores(filtered,scorePage);renderStats(filtered);renderPopClass(scores);}
async function toggleTheme(){const theme=document.documentElement.dataset.theme==="dark"?"light":"dark";setTheme(theme);try{await saveDisplayPreferences({theme});}catch(error){alert(`表示設定を保存できませんでした：${error.message||error}`);}}
function populateLevels(){const selects=[$("#levelFilter"),$("#defaultLevelFilter"),$("#adminLevelFilter")];for(let level=50;level>=1;level--){for(const select of selects){const option=document.createElement("option");option.value=String(level);option.textContent=`Lv.${level}`;select.append(option);}}const saved=localStorage.getItem("popn-default-level")||"ALL";for(const select of selects.slice(0,2))select.value=[...select.options].some(x=>x.value===saved)?saved:"ALL";}
async function populateAdminMasterFilters(){const select=$("#adminVersionFilter"),current=select.value,versions=await loadVersions();select.innerHTML='<option value="ALL">全バージョン</option>'+versions.map(x=>`<option value="${attr(x.id)}">${attr(x.name)}</option>`).join("");select.value=[...select.options].some(x=>x.value===current)?current:"ALL";}
function syncNotice(){let box=document.querySelector("#syncSaveNotice");if(box)return box;box=document.createElement("div");box.id="syncSaveNotice";Object.assign(box.style,{position:"fixed",left:"12px",right:"12px",bottom:"12px",zIndex:"2147483647",maxWidth:"520px",margin:"0 auto",padding:"12px 14px",border:"2px solid var(--line,#334b93)",borderRadius:"12px",background:"var(--page,#fff)",color:"var(--text,#17244d)",boxShadow:"0 4px 18px #0004",fontSize:"14px"});box.innerHTML='<strong>スコアを保存中</strong><div data-sync-save-status>準備中…</div><progress data-sync-save-progress value="0" max="1" style="width:100%;margin-top:6px"></progress>';document.body.appendChild(box);return box;}
function applySyncedRecordsLocally(records){const map=new Map(records.map(row=>[`${row.master_key}|${String(row.chart||"").toUpperCase()}`,row]));let changed=false;scores=scores.map(row=>{const incoming=map.get(`${row.master_key}|${String(row.chart||"").toUpperCase()}`);if(!incoming)return row;changed=true;const official=Math.max(0,Math.min(100000,Number(incoming.score)||0)),version=Math.max(0,Math.min(100000,Number(incoming.version_score)||0)),manual=Math.max(0,Math.min(100000,Number(row.manual_history_score)||0));return{...row,official_score:official,version_score:version,score:Math.max(official,version,manual),medal_code:incoming.medal_code||"none",rank_code:incoming.rank_code||rankFromScore(version,incoming.medal_code),source:"sync"};});if(changed)applyFilters(false);}
async function importHash(){const marker="#popn-sync-gzip=";if(!location.hash.startsWith(marker))return;const notice=syncNotice(),status=notice.querySelector("[data-sync-save-status]"),progress=notice.querySelector("[data-sync-save-progress]");try{const binary=atob(decodeURIComponent(location.hash.slice(marker.length))),bytes=Uint8Array.from(binary,char=>char.charCodeAt(0)),text=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"))).text(),payload=JSON.parse(text);if(payload.type!=="POPN_SCORE_SYNC"||!Array.isArray(payload.records))throw new Error("同期データが不正です。");history.replaceState(null,"",location.pathname+location.search);applySyncedRecordsLocally(payload.records);progress.max=Math.max(1,payload.records.filter(x=>Number(x.score)>0).length);status.textContent=`0/${progress.max}譜面を保存中（画面には取得結果を先に反映しています）`;const result=await syncScores(payload.records,info=>{progress.max=Math.max(1,info.total);progress.value=info.done;status.textContent=`${info.done}/${info.total}譜面を保存中${info.retries?`・再試行 ${info.retries}回`:""}`;});progress.value=progress.max;status.textContent=`保存完了：${result.saved}譜面・曲マスター未登録 ${result.unmatched}譜面`;await refreshAuth();setTimeout(()=>notice.remove(),2500);if(result.failed)alert(`${result.failed}譜面だけ保存できませんでした。時間をおいてもう一度同期してください。`);}catch(error){status.textContent=`保存エラー：${error.message||error}`;notice.querySelector("strong").textContent="同期データの保存に失敗しました";alert(`同期に失敗しました：${error.message||error}`);}}

populateLevels();setTheme(localStorage.getItem("popn-theme")==="dark"?"dark":"light");$("#setupNotice").hidden=isConfigured;
let lockedScroll=0;function syncDialogLock(){const open=Boolean(document.querySelector("dialog[open]")),locked=document.body.classList.contains("modal-open");if(open&&!locked){lockedScroll=window.scrollY;document.body.classList.add("modal-open");document.body.style.top=`-${lockedScroll}px`;}else if(!open&&locked){document.body.classList.remove("modal-open");document.body.style.top="";window.scrollTo(0,lockedScroll);}}for(const dialog of document.querySelectorAll("dialog")){dialog.addEventListener("close",()=>queueMicrotask(syncDialogLock));new MutationObserver(syncDialogLock).observe(dialog,{attributes:true,attributeFilter:["open"]});}for(const button of document.querySelectorAll("[data-dialog-close]"))button.addEventListener("click",()=>button.closest("dialog").close());for(const button of document.querySelectorAll("[data-menu-back]"))button.addEventListener("click",()=>{const dialog=button.closest("dialog");if(dialog?.open)dialog.close();queueMicrotask(()=>$("#menuDialog").showModal());});
function showNotice(message){const dialog=$("#noticeDialog");$("#noticeMessage").textContent=String(message??"");if(dialog.open)dialog.close();dialog.showModal();}window.alert=showNotice;
function askConfirm(message){const dialog=$("#confirmDialog");$("#confirmMessage").textContent=String(message??"");return new Promise(resolve=>{dialog.addEventListener("close",()=>resolve(dialog.returnValue==="ok"),{once:true});dialog.showModal();});}
function askText(message){const dialog=$("#promptDialog"),input=$("#promptInput");$("#promptLabel").textContent=String(message??"");input.value="";return new Promise(resolve=>{dialog.addEventListener("close",()=>resolve(dialog.returnValue==="ok"?input.value:null),{once:true});dialog.showModal();queueMicrotask(()=>input.focus());});}
$("#menuButton").addEventListener("click",()=>$("#menuDialog").showModal());$("#settingsThemeButton").addEventListener("click",toggleTheme);
$("#defaultLevelFilter").addEventListener("change",async event=>{const value=event.target.value;localStorage.setItem("popn-default-level",value);$("#levelFilter").value=value;applyFilters(true);try{await saveDisplayPreferences({defaultLevel:value});}catch(error){alert(`表示設定を保存できませんでした：${error.message||error}`);}});
async function refreshUsers(reset=false){if(reset)userPage=1;userRows=await loadUsers($("#userSearchInput").value);userPage=renderUsers(userRows,userPage);}
for(const button of document.querySelectorAll(".tabs button"))button.addEventListener("click",async()=>{if(button.dataset.tab==="admin"&&!admin)return;showTab(button.dataset.tab);if(button.dataset.tab==="admin")await renderAdmin();if(button.dataset.tab==="users"&&isConfigured){try{await refreshUsers(false);}catch(error){alert(error.message||error);}}});
for(const selector of["#searchInput","#levelFilter","#versionFilter","#medalFilter","#rankFilter"])$(selector).addEventListener(selector==="#searchInput"?"input":"change",()=>applyFilters(true));
const DEFAULT_SCORE_SORT_ORDER={level:"desc",medal:"asc",score:"desc",version_score:"desc",pop_class:"desc"};
$("#scoreSortField").addEventListener("change",()=>{$("#scoreSortOrder").value=DEFAULT_SCORE_SORT_ORDER[$("#scoreSortField").value]||"asc";applyFilters(true);});
$("#scoreSortOrder").addEventListener("change",()=>applyFilters(true));
$("#reloadButton").addEventListener("click",event=>{event.currentTarget.classList.add("is-loading");location.reload();});
function setAuthMode(mode){authMode=mode==="register"?"register":"login";const loginMode=authMode==="login",password=$("#authGateForm input[name=password]"),confirmRow=$("#authGatePasswordConfirmRow"),confirmInput=$("#authGateForm input[name=password_confirm]"),notice=$("#authGatePasswordNotice");$("#gateLoginTab").classList.toggle("active",loginMode);$("#gateRegisterTab").classList.toggle("active",!loginMode);$("#gateLoginTab").setAttribute("aria-selected",String(loginMode));$("#gateRegisterTab").setAttribute("aria-selected",String(!loginMode));$("#authGateTitle").textContent=loginMode?"ログイン":"新規登録";$("#authGateForm button[type=submit]").textContent=loginMode?"ログイン":"新規登録";password.autocomplete=loginMode?"current-password":"new-password";password.minLength=loginMode?6:8;password.placeholder=loginMode?"パスワードを入力":"8文字以上で設定";confirmRow.hidden=loginMode;notice.hidden=loginMode;confirmInput.required=!loginMode;if(loginMode)confirmInput.value="";$("#authGateError").textContent="";}
$("#gateLoginTab").addEventListener("click",()=>setAuthMode("login"));$("#gateRegisterTab").addEventListener("click",()=>setAuthMode("register"));
$("#authGateForm").addEventListener("submit",async event=>{event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement),submit=formElement.querySelector("button[type=submit]"),password=String(form.get("password")||"");$("#authGateError").textContent="";submit.disabled=true;try{if(authMode==="login")await login(form.get("username"),password);else{if(password.length<8)throw new Error("パスワードは8文字以上で入力してください。");if(password!==String(form.get("password_confirm")||""))throw new Error("確認用パスワードが一致しません。");await register(form.get("username"),password);}formElement.reset();setAuthMode("login");await refreshAuth();}catch(error){$("#authGateError").textContent=error.message||error;}finally{submit.disabled=false;}});
$("#logoutButton").addEventListener("click",async()=>{$("#myPageDialog").close();await logout();await refreshAuth();});
$("#manualButton").addEventListener("click",async()=>{if(!await currentUser()){alert("追加依頼を送るにはログインしてください。");return;}$("#songRequestForm").reset();$("#songRequestDialog .error").textContent="";$("#songRequestDialog").showModal();});$("#syncHelpButton").addEventListener("click",()=>{$("#menuDialog").close();$("#syncDialog").showModal();});
function updateCoolPerfectPreview(){const button=$("#medalPickerButton"),image=button.querySelector("img"),label=button.querySelector("span"),history=Math.max(0,Number($("#manualHistoryScore").value)||0),current=Math.max(0,Number($("#manualScoreInput").value)||0),cool=Math.max(history,current)===100000,info=medalInfo($("#manualForm [name=medal_code]").value);button.classList.toggle("cool-perfect-active",cool);button.disabled=cool;if(cool){image.src="./assets/cool-perfect.png";image.alt="COOL PERFECT";image.hidden=false;label.hidden=true;}else{image.src=info.url;image.alt=info.label;image.hidden=!info.url;label.textContent=info.url?"":info.label==="－　未プレー"?"－":info.label;label.hidden=Boolean(info.url);}button.setAttribute("aria-label",cool?"COOL PERFECT（100000点で自動）":info.label);button.title=cool?"COOL PERFECT（100000点で自動）":info.label;}
function updateRankPreview(score){const medal=$("#manualForm [name=medal_code]").value,value=rankFromScore(score,medal),slug=value.replace("+","plus").toLowerCase(),el=$("#manualRank");el.className=`rank-text rank-${slug}`;el.textContent=value;el.setAttribute("aria-label",value);el.title=value;$("#manualPopClass").textContent=songPopClass(selectedSong,score,Math.max(Number($("#manualHistoryScore").value)||0,Number(score)||0)===100000?"perfect":medal).toFixed(2);updateCoolPerfectPreview();}$("#manualScoreInput").addEventListener("input",event=>updateRankPreview(event.target.value));$("#manualHistoryScore").addEventListener("input",()=>updateRankPreview($("#manualScoreInput").value));
$("#manualForm").addEventListener("submit",async event=>{event.preventDefault();if(!selectedSong){$("#manualError").textContent="曲マスターから譜面を選択してください。";return;}const formElement=event.currentTarget,form=new FormData(formElement),historyScore=historyValueForSave(),versionScore=Math.max(0,Math.min(100000,Number(form.get("version_score"))||0)),medalCode=Math.max(historyScore,versionScore)===100000?"perfect":String(form.get("medal_code")||"none"),row=selectedSong;try{await saveScore(row.song_id||row.id,row.chart,historyScore,versionScore,medalCode);Object.assign(row,{manual_history_score:historyScore,version_score:versionScore,score:Math.max(Number(row.official_score)||0,historyScore,versionScore),medal_code:medalCode,rank_code:rankFromScore(versionScore,medalCode),source:"manual"});$("#manualDialog").close();formElement.reset();updateRankPreview(0);selectedSong=null;editingScoreId=null;applyFilters(false);}catch(error){$("#manualError").textContent=error.message||error;}});
async function openScoreEditor(button){if(!await currentUser()){alert("スコアを登録するにはログインしてください。");return;}const row=scores.find(x=>x.id===button.dataset.editScore);if(!row)return;editingScoreId=row.id;selectedSong=row;$("#songGenreInput").value=row.genre;$("#songTitleInput").value=`${row.title} / ${row.chart} ${row.level}`;$("#manualArtist").textContent=`アーティスト：${row.artist}`;$("#manualArtist").hidden=false;$("#manualVersion").textContent=`登場バージョン：${row.version_name||"未設定"}`;$("#manualVersion").hidden=false;$("#songGenreInput").disabled=true;$("#songTitleInput").disabled=true;setHistoryInput(row);$("#historyScoreGuide").textContent="今作スコアが上回る場合は同じ値を表示します";$("#manualScoreInput").value=row.version_score||0;chooseMedal(row.medal_code);updateRankPreview(row.version_score||0);$("#manualError").textContent="";$("#manualDialog h2").textContent="登録スコアを編集";$("#manualDialog").showModal();}
$("#scoreList").addEventListener("click",async event=>{const pager=event.target.closest("[data-score-page]");if(pager&&!pager.disabled){scorePage=Number(pager.dataset.scorePage);applyFilters(false);$("#scoreList").scrollIntoView({behavior:"smooth",block:"start"});return;}const button=event.target.closest("[data-edit-score]");if(button)await openScoreEditor(button);});
$("#popclassContent").addEventListener("click",async event=>{const button=event.target.closest("[data-edit-score]");if(button)await openScoreEditor(button);});
$("#scoreList").addEventListener("change",event=>{if(event.target.matches("[data-score-page-select]")){scorePage=Number(event.target.value);applyFilters(false);$("#scoreList").scrollIntoView({behavior:"smooth",block:"start"});}});
$("#masterFileInput").addEventListener("change",async event=>{const file=event.target.files?.[0];if(!file)return;try{const count=await importSongMaster(file);await refreshAuth();if(currentAdminTab()==="master")await renderAdmin();alert(`${count}曲を曲マスターへ登録・更新しました。`);}catch(error){alert(`曲マスター投入に失敗しました：${error.message||error}`);}finally{event.target.value="";}});
$("#masterDownloadButton").addEventListener("click",async()=>{try{const count=await downloadSongMaster();alert(`${count}曲の曲マスターをダウンロードしました。`);}catch(error){alert(`曲マスターのダウンロードに失敗しました：${error.message||error}`);}});
$("#userSearchInput").addEventListener("input",wait(()=>refreshUsers(true).catch(console.error),350));$("#userList").addEventListener("click",async event=>{const copyButton=event.target.closest("[data-copy-poptomo]");if(copyButton){try{await writeClipboard(copyButton.dataset.copyPoptomo);alert("ポプともIDをコピーしました。");}catch(error){alert(`コピーできませんでした：${error.message||error}`);}return;}const pageButton=event.target.closest("[data-user-page]");if(pageButton&&!pageButton.disabled){userPage=Number(pageButton.dataset.userPage);renderUsers(userRows,userPage);}});$("#userList").addEventListener("change",event=>{if(event.target.matches("[data-user-page-select]")){userPage=Number(event.target.value);renderUsers(userRows,userPage);}});
for(const selector of["#userSortField","#userSortOrder"])$(selector).addEventListener("change",()=>{userPage=1;userPage=renderUsers(userRows,userPage);});
const feedbackEsc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
async function renderFeedbackHistory(){const box=$("#feedbackHistory");box.innerHTML='<div class="empty">読み込み中…</div>';try{const rows=await loadFeedbackHistory();box.innerHTML=rows.length?rows.map(x=>`<article class="feedback-history-card"><div class="feedback-card-title"><strong>${x.category==="bug"?"不具合":"要望"}</strong><span class="status ${feedbackEsc(x.status)}">${x.status==="resolved"?"解決済み":x.status==="answered"?"返信済み":"受付済み"}</span></div><p>${feedbackEsc(x.message)}</p>${x.device_name||x.browser_name?`<small>機種：${feedbackEsc(x.device_name||"－")} / ブラウザ：${feedbackEsc(x.browser_name||"－")}</small>`:""}${x.admin_reply?`<div class="admin-reply"><small>管理者からの返信</small>${feedbackEsc(x.admin_reply)}</div>`:""}<time>${new Date(x.created_at).toLocaleString("ja-JP")}</time></article>`).join(""):'<div class="empty">送信履歴はありません。</div>';}catch(error){box.innerHTML=`<p class="error">${feedbackEsc(error.message||error)}</p>`;}}
$("#feedbackButton").addEventListener("click",async()=>{$("#menuDialog").close();$("#feedbackDialog").showModal();await renderFeedbackHistory();});
$("#songRequestForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,errorBox=form.querySelector(".error"),values=Object.fromEntries(new FormData(form)),charts=[["LIGHT","light_level"],["NORMAL","normal_level"],["HYPER","hyper_level"],["EX","ex_level"]].filter(([,key])=>String(values[key]||"").trim());if(!charts.length){errorBox.textContent="少なくとも1つの譜面レベルを入力してください。";return;}errorBox.textContent="";try{const results=[];for(const[chart,key]of charts)results.push(await submitSongRequest({...values,chart,level:values[key]}));form.reset();$("#songRequestDialog").close();alert(results.every(result=>result==="merged")?"既存の曲マスターに統合しました。":"登録依頼を送信しました。");}catch(error){errorBox.textContent=error.message||error;}});
$("#feedbackForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,errorBox=event.currentTarget.querySelector(".error");try{await submitFeedback(Object.fromEntries(new FormData(form)));form.reset();await renderFeedbackHistory();alert("送信しました。");}catch(error){errorBox.textContent=error.message||error;}});
function chooseMedal(code){const info=medalInfo(code),input=$("#manualForm [name=medal_code]"),button=$("#medalPickerButton"),image=button.querySelector("img"),label=button.querySelector("span");input.value=code;image.src=info.url;image.hidden=!info.url;label.textContent=info.url?"":code==="none"?"－":info.label;label.hidden=Boolean(info.url);button.title=info.label;button.setAttribute("aria-label",info.label);$("#medalPicker").hidden=true;updateRankPreview($("#manualScoreInput").value);}
$("#medalPicker").innerHTML=MEDALS.map(([code,label,file])=>`<button type="button" data-medal="${code}">${file?`<img src="https://eacache.s.konaminet.jp/game/popn/popn29/images/p/howto/more/${file}" alt="">`:""}<span>${label}</span></button>`).join("");
$("#medalPickerButton").addEventListener("click",()=>{$("#medalPicker").hidden=!$("#medalPicker").hidden;});
$("#medalPicker").addEventListener("click",event=>{const button=event.target.closest("[data-medal]");if(button)chooseMedal(button.dataset.medal);});chooseMedal("none");
const filterMedals=[["ALL","全メダル",""],...MEDALS];$("#filterMedalPicker").innerHTML=filterMedals.map(([code,label,file])=>`<button type="button" data-filter-medal="${code}">${code==="ALL"?`<span class="filter-medal-all">全メダル</span>`:file?`<img src="https://eacache.s.konaminet.jp/game/popn/popn29/images/p/howto/more/${file}" alt=""><span>${label}</span>`:`<span class="filter-medal-empty">－</span><span>${label.replace(/^－\s*/,"")}</span>`}</button>`).join("");function chooseFilterMedal(code){const button=$("#filterMedalButton"),image=button.querySelector("img"),label=button.querySelector("span"),info=code==="ALL"?{label:"全メダル",url:""}:medalInfo(code);$("#medalFilter").value=code;image.src=info.url;image.hidden=!info.url;label.textContent=code==="none"?"－":info.label;label.hidden=Boolean(info.url);button.title=info.label;button.setAttribute("aria-label",`メダル：${info.label}`);}$("#filterMedalButton").addEventListener("click",()=>{$("#filterMedalPicker").hidden=!$("#filterMedalPicker").hidden;});$("#filterMedalPicker").addEventListener("click",event=>{const button=event.target.closest("[data-filter-medal]");if(!button)return;chooseFilterMedal(button.dataset.filterMedal);$("#filterMedalPicker").hidden=true;$("#medalFilter").dispatchEvent(new Event("change"));});chooseFilterMedal("ALL");
async function writeClipboard(text){try{await navigator.clipboard.writeText(text);}catch{const area=document.createElement("textarea");area.value=text;area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();const copied=document.execCommand("copy");area.remove();if(!copied)throw new Error("クリップボードへ書き込めませんでした。");}}
async function copyTool(file){const response=await fetch(`./tools/${file}`,{cache:"no-store"});if(!response.ok)throw new Error("コードを読み込めませんでした。");const text=await response.text();await writeClipboard(text);return file.includes("score-sync")?"同期用コードをコピーしました。ブックマークのURL欄へ貼り付けてください。":"抽出コードをコピーしました。公式サイトのConsoleへ貼り付けてください。";}
$("#copySyncButton").addEventListener("click",async()=>{const status=$(".sync-status");try{await copyTool("popn-score-sync.txt");status.textContent="コードをコピーしました";}catch(error){status.textContent=`コピー失敗：${error.message||error}`;}});
$("#myPageButton").addEventListener("click",async()=>{const user=await currentUser();if(!user){alert("マイページを利用するにはログインしてください。");return;}const profile=await loadMyProfile();$("#newUsernameInput").value=profile.username;$("#poptomoIdInput").value=profile.poptomo_id||"";$("#poptomoPublicInput").checked=Boolean(profile.poptomo_public);$("#menuDialog").close();$("#myPageDialog").showModal();});
$("#poptomoForm").addEventListener("submit",async event=>{event.preventDefault();const errorBox=event.currentTarget.querySelector(".error");try{await savePoptomo($("#poptomoIdInput").value,$("#poptomoPublicInput").checked);errorBox.textContent="";alert("ポプとも設定を保存しました。");}catch(error){errorBox.textContent=error.message||error;}});
$("#usernameForm").addEventListener("submit",async event=>{event.preventDefault();const errorBox=event.currentTarget.querySelector(".error");try{const name=await changeUsername(new FormData(event.currentTarget).get("username"));$("#playerName").textContent=name;errorBox.textContent="";alert("ユーザー名を変更しました。次回から新しいユーザー名でログインしてください。");}catch(error){errorBox.textContent=error.message||error;}});
$("#passwordForm").addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget),password=String(form.get("password")||""),confirm=String(form.get("password_confirm")||""),errorBox=event.currentTarget.querySelector(".error");if(password!==confirm){errorBox.textContent="確認用パスワードが一致しません。";return;}try{await changePassword(password);event.currentTarget.reset();errorBox.textContent="";alert("パスワードを変更しました。");}catch(error){errorBox.textContent=error.message||error;}});
document.querySelector('[data-copy-tool="master"]').addEventListener("click",()=>copyTool("popn-master-extractor.txt").then(alert).catch(error=>alert(error.message||error)));
$("#adminClearMyScoresButton").addEventListener("click",async()=>{if(!await askConfirm("管理者アカウントに登録されている全スコアデータを削除しますか？\nこの操作は取り消せません。"))return;try{await clearMyRegisteredScores();await refreshAuth();alert("管理者アカウントの登録データをすべて削除しました。");}catch(error){alert(`一括削除に失敗しました：${error.message||error}`);}});
for(const button of document.querySelectorAll("[data-admin-tab]"))button.addEventListener("click",()=>setAdminTab(button.dataset.adminTab));
$("#adminSearch").addEventListener("input",wait(event=>setAdminSearch(event.target.value),300));
for(const selector of["#adminLevelFilter","#adminVersionFilter","#adminChartFilter"])$(selector).addEventListener("change",()=>setAdminMasterFilters({level:$("#adminLevelFilter").value,version:$("#adminVersionFilter").value,chart:$("#adminChartFilter").value}));
async function openAdminEditor(kind,item={}){adminEdit={kind,item};const fields=$("#adminEditFields");if(kind==="version"){$("#adminEditTitle").textContent=item.id?"バージョン編集":"バージョン追加";fields.innerHTML=`<label>表示名<input name="name" required value="${attr(item.name)}"></label><label>識別名<input name="slug" required pattern="[a-z0-9_-]+" value="${attr(item.slug)}"></label><label>並び順<input name="sort_order" type="number" required value="${item.sort_order??0}"></label><label class="check-row"><input name="is_current" type="checkbox" ${item.is_current?"checked":""}>現行バージョン</label><label class="check-row"><input name="is_active" type="checkbox" ${item.is_active!==false?"checked":""}>有効</label>`;}else{const versions=await loadVersions(),generated=[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,"0")).join("");$("#adminEditTitle").textContent=item.id?"曲マスター編集":"曲マスター追加";fields.innerHTML=`<label>曲ID<input name="master_key" readonly value="${attr(item.master_key||generated)}"><small>新規追加時は自動設定されます。</small></label><label>バナー画像URL（任意）<input name="banner_url" type="url" value="${attr(item.banner_url)}" placeholder="https://..."></label><label class="banner-upload">バナー画像をアップロード（任意）<input name="banner_file" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><small>画像を選ぶとURLより優先します（2MB以下）。</small></label><div class="form-grid"><label>ジャンル<input name="genre" required value="${attr(item.genre)}"></label><label>曲名<input name="title" required value="${attr(item.title)}"></label></div><label>アーティスト<input name="artist" required value="${attr(item.artist)}"></label><div class="master-levels">${[["LIGHT","light_level"],["NORMAL","normal_level"],["HYPER","hyper_level"],["EX","ex_level"]].map(([label,key])=>`<label>${label}<input name="${key}" type="number" min="1" max="50" value="${item[key]||""}" placeholder="なし"></label>`).join("")}</div><label>登場バージョン<select name="version_id"><option value="">未設定</option>${versions.map(x=>`<option value="${x.id}" ${x.id===item.version_id?"selected":""}>${attr(x.name)}</option>`).join("")}</select></label>`;}$("#adminEditDialog").showModal();}
$("#adminAddButton").addEventListener("click",()=>openAdminEditor(currentAdminTab()==="versions"?"version":"song"));
$("#adminContent").addEventListener("click",async event=>{const song=event.target.closest("[data-edit-song]"),version=event.target.closest("[data-edit-version]"),approve=event.target.closest("[data-approve-request]"),status=event.target.closest("[data-status-id]"),reply=event.target.closest("[data-reply-id]"),remove=event.target.closest("[data-delete-user]"),removeFeedback=event.target.closest("[data-delete-feedback]");try{if(song)await openAdminEditor("song",JSON.parse(decodeURIComponent(song.dataset.editSong)));if(version)await openAdminEditor("version",JSON.parse(decodeURIComponent(version.dataset.editVersion)));if(approve){await approveSongRequest(approve.dataset.approveRequest);await renderAdmin();alert("曲マスターへ登録・統合しました。");}if(status){await updateStatus(status.dataset.statusTable,status.dataset.statusId,status.dataset.status);await renderAdmin();}if(reply){const message=await askText("ユーザーへの返信を入力してください。");if(message!==null&&message.trim()){await updateStatus("feedback_reports",reply.dataset.replyId,"answered",message.trim());await renderAdmin();}}if(removeFeedback&&await askConfirm("この要望・不具合を削除しますか？")){await deleteFeedback(removeFeedback.dataset.deleteFeedback);await renderAdmin();alert("削除しました。");}if(remove&&await askConfirm(`${decodeURIComponent(remove.dataset.userName)} を削除しますか？\nスコアなど、このユーザーのデータも削除されます。`)){await deleteUser(remove.dataset.deleteUser);await renderAdmin();alert("ユーザーを削除しました。");}}catch(error){alert(error.message||error);}});
$("#adminContent").addEventListener("click",event=>{const button=event.target.closest("[data-admin-page]");if(button&&!button.disabled)setAdminPage(button.dataset.adminPage);});$("#adminContent").addEventListener("change",event=>{if(event.target.matches("[data-admin-page-select]"))setAdminPage(event.target.value);});
$("#adminEditForm").addEventListener("submit",async event=>{event.preventDefault();const raw=Object.fromEntries(new FormData(event.currentTarget)),errorBox=event.currentTarget.querySelector(".error");try{if(adminEdit.kind==="version")await saveVersion({...raw,is_current:event.currentTarget.elements.is_current.checked,is_active:event.currentTarget.elements.is_active.checked},adminEdit.item.id);else{const file=event.currentTarget.elements.banner_file?.files?.[0];if(file)raw.banner_url=await uploadSongBanner(file);await saveSong(raw,adminEdit.item.id);}$("#adminEditDialog").close();await renderAdmin();}catch(error){errorBox.textContent=error.message||error;}});
onAuthChange(()=>refreshAuth(false));await refreshAuth();await importHash();
