import{requireDb}from"./supabase.js";

export async function submitSongRequest(values){const client=requireDb(),{data,error}=await client.rpc("submit_song_request_v2",{p_genre:values.genre.trim(),p_title:values.title.trim(),p_artist:values.artist.trim(),p_chart:values.chart,p_level:Number(values.level),p_note:values.note.trim()});if(error)throw error;return data;}
export async function submitFeedback(values){const message=String(values.message||"").trim();if(!message)throw new Error("内容を入力してください。");const client=requireDb();const{error}=await client.from("feedback_reports").insert({category:values.category,message,device_name:String(values.device_name||"").trim(),browser_name:String(values.browser_name||"").trim(),page_url:location.href,user_agent:navigator.userAgent});if(error)throw error;}
export async function loadFeedbackHistory(){const{data,error}=await requireDb().from("feedback_reports").select("id,category,message,device_name,browser_name,status,admin_reply,created_at,updated_at").order("created_at",{ascending:false}).limit(100);if(error)throw error;return data||[];}

const BANNER_REQUEST_TYPES={"image/png":"png","image/jpeg":"jpg","image/webp":"webp","image/gif":"gif"};
export async function loadBannerRequestSongs(){const{data,error}=await requireDb().rpc("list_banner_request_songs");if(error)throw error;return data||[];}
export async function submitBannerRequest(songId,file){if(!songId)throw new Error("対象曲を選択してください。");if(!file?.size)throw new Error("バナー画像を選択してください。");const ext=BANNER_REQUEST_TYPES[file.type];if(!ext)throw new Error("PNG・JPEG・WebP・GIF画像を選択してください。");if(file.size>2*1024*1024)throw new Error("バナー画像は2MB以下にしてください。");const db=requireDb(),{data:{user},error:userError}=await db.auth.getUser();if(userError)throw userError;if(!user)throw new Error("ログインが必要です。");const path=`${user.id}/${crypto.randomUUID()}.${ext}`,upload=await db.storage.from("banner-requests").upload(path,file,{cacheControl:"31536000",contentType:file.type,upsert:false});if(upload.error)throw upload.error;const{data,error}=await db.rpc("submit_banner_request",{p_song_id:songId,p_image_path:path});if(error){await db.storage.from("banner-requests").remove([path]).catch(()=>{});throw error;}return data;}
