import{popClassSelection,rankFromScore,songPopClass}from"./scores.js";

const BASE="https://eacache.s.konaminet.jp/game/popn/popn29/images/p/";
const PAGE_SIZE=50;
export const MEDALS=[
 ["none","－　未プレー",""],
 ["perfect","PERFECT","perfect_00.png"],["fc_1_5","FC・GOOD 1～5","full_combo_00.png"],["fc_6_20","FC・GOOD 6～20","full_combo_01.png"],["fc_21_plus","FC・GOOD 21以上","full_combo_02.png"],["clear_bad_1_5","クリア・BAD 1～5","bad_00.png"],["clear_bad_6_20","クリア・BAD 6～20","bad_01.png"],
 ["clear_bad_21_plus","クリア・BAD 21以上","bad_02.png"],["long_off","ロングオフ","long_off.png"],["easy","EASYクリア","easy.png"],["failed_15_16","FAILED・15～16粒","groove_00.png"],["failed_12_14","FAILED・12～14粒","groove_01.png"],["failed_0_11","FAILED・11粒以下","groove_02.png"]
];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
export function medalInfo(code){const key=String(code||"none").toLowerCase(),logical=MEDALS.find(x=>x[0]===key);if(logical)return{label:logical[1],url:logical[2]?BASE+"howto/more/"+logical[2]:""};return{label:key==="f"?"FAILED":key.toUpperCase(),url:BASE+"common/medal/meda_big_"+key+".png"};}
export function setTheme(theme){const v=theme==="dark"?"dark":"light";document.documentElement.dataset.theme=v;const headerButton=document.querySelector("#themeButton");if(headerButton)headerButton.textContent=v==="light"?"☾":"☀";document.querySelector("#themeLabel").textContent=v==="light"?"ライト":"ダーク";localStorage.setItem("popn-theme",v);}
function pager(current,pages,attr){const options=Array.from({length:pages},(_,i)=>`<option value="${i+1}" ${i+1===current?"selected":""}>${i+1} / ${pages}</option>`).join("");return `<div class="pager-controls"><button type="button" data-${attr}="${current-1}" ${current===1?"disabled":""} aria-label="前のページ">◀</button><label class="pager-select"><select data-${attr}-select aria-label="ページを選択">${options}</select></label><button type="button" data-${attr}="${current+1}" ${current===pages?"disabled":""} aria-label="次のページ">▶</button></div>`;}
function scoreCard(row){const medal=medalInfo(row.medal_code),r=rankFromScore(row.score,row.medal_code),slug=r.replace("+","plus").toLowerCase(),noScore=Number(row.score)<=0&&Number(row.version_score)<=0,medalMissing=String(row.medal_code||"none").toLowerCase()==="none",medalHtml=medalMissing?'<span class="unplayed-mark">－</span>':medal.url?`<img src="${medal.url}" alt="${esc(medal.label)}" title="${esc(medal.label)}">`:`<span>${esc(medal.label)}</span>`,pc=songPopClass(row);return `<article class="score-card-v300">${row.banner_url?`<img class="song-banner" src="${esc(row.banner_url)}" alt="" loading="lazy">`:'<div class="song-banner banner-empty">NO IMAGE</div>'}<span class="card-medal">${medalHtml}</span>${noScore?'<span class="card-rank">－</span>':`<strong class="card-rank rank-text rank-${slug}">${r}</strong>`}<span class="card-score card-history"><small>歴代</small><strong>${Number(row.score)>0?Number(row.score):"－"}</strong></span><span class="card-score card-current"><small>今作</small><strong>${Number(row.version_score)>0?Number(row.version_score):"－"}</strong></span><span class="card-popclass"><small>ポックラ</small><strong>${pc.toFixed(2)}</strong></span><span class="card-chart ${row.chart.toLowerCase()}">${row.chart}</span><span class="card-genre">${esc(row.genre)}</span><strong class="card-level">${row.level}</strong><h2 class="card-title">${esc(row.title)}</h2><button class="score-edit" type="button" data-edit-score="${row.id}">編集</button></article>`;}
export function renderScores(rows,page=1){const list=document.querySelector("#scoreList");if(!rows.length){list.innerHTML='<div class="empty">条件に合う曲がありません。</div>';return 1;}const chartOrder={EX:0,HYPER:1,NORMAL:2,LIGHT:3},field=document.querySelector("#scoreSortField")?.value||"medal",direction=document.querySelector("#scoreSortOrder")?.value==="desc"?-1:1,medalOrder=code=>{const normalized=String(code||"none").toLowerCase(),index=MEDAL_GROUPS.findIndex(([,codes])=>codes.includes(normalized));return index<0?MEDAL_GROUPS.length:index;},value=row=>field==="pop_class"?songPopClass(row):Number(row[field]||0),compare=(a,b)=>{const result=field==="medal"?medalOrder(a.medal_code)-medalOrder(b.medal_code):value(a)-value(b);return result*direction||String(a.title||"").localeCompare(String(b.title||""),"ja")||(chartOrder[a.chart]??9)-(chartOrder[b.chart]??9);},sorted=[...rows].sort(compare),pages=Math.ceil(sorted.length/PAGE_SIZE),current=Math.min(Math.max(1,Number(page)||1),pages),start=(current-1)*PAGE_SIZE;list.innerHTML=sorted.slice(start,start+PAGE_SIZE).map(scoreCard).join("")+`<nav class="score-pager"><span>${sorted.length.toLocaleString("ja-JP")}件中 ${(start+1).toLocaleString("ja-JP")}～${Math.min(start+PAGE_SIZE,sorted.length).toLocaleString("ja-JP")}件</span>${pager(current,pages,"score-page")}</nav>`;return current;}
export function renderPopClass(rows){const{current,other,total}=popClassSelection(rows),section=(title,items,limit)=>`<section class="popclass-group"><div class="popclass-group-title"><h2>${title}</h2><span>${items.length}/${limit}曲</span></div><div class="score-list">${items.length?items.map(scoreCard).join(""):'<div class="empty">対象曲がありません。</div>'}</div></section>`;document.querySelector("#totalPopClass").textContent=total.toFixed(2);document.querySelector("#popclassContent").innerHTML=section("今作",current,20)+section("その他",other,40);return total;}
const MEDAL_GROUPS=[
 ["perfect",["perfect","a"]],["fc_1_5",["fc_1_5","b"]],["fc_6_20",["fc_6_20","c"]],["fc_21_plus",["fc_21_plus","d"]],
 ["clear_bad_1_5",["clear_bad_1_5","e"]],["clear_bad_6_20",["clear_bad_6_20","f"]],["clear_bad_21_plus",["clear_bad_21_plus","g"]],
 ["long_off",["long_off"]],["easy",["easy","k"]],["failed_15_16",["failed_15_16","h","l"]],["failed_12_14",["failed_12_14","i","m"]],["failed_0_11",["failed_0_11","j","n"]],["none",["none"]]
];
export function renderStats(rows){const code=x=>String(x.medal_code||"none").toLowerCase(),noPlay=x=>Number(x.score)<=0&&Number(x.version_score)<=0&&code(x)==="none",registered=rows.filter(x=>!noPlay(x)),unplayed=registered.filter(x=>code(x)==="none"),failed=x=>/^(h|i|j|l|m|n)$/.test(code(x))||code(x).startsWith("failed_"),clear=registered.filter(x=>code(x)!=="none"&&!failed(x)),rate=`${(clear.length/Math.max(1,registered.length)*100).toFixed(2)}%`,groups=MEDAL_GROUPS.filter(([key])=>key!=="none"),counts=new Map(groups.map(([key,codes])=>[key,registered.filter(x=>codes.includes(code(x))).length])),medals=groups.map(([key])=>{const info=medalInfo(key);return `<div class="medal-stat" title="${esc(info.label)}"><img src="${info.url}" alt="${esc(info.label)}"><strong>${counts.get(key).toLocaleString("ja-JP")}</strong></div>`;}).join("")+`<div class="medal-stat unplayed-stat" title="未プレー"><span aria-label="未プレー">－</span><strong>${unplayed.length.toLocaleString("ja-JP")}</strong></div><div class="medal-stat no-play-stat"><span class="no-play-label">NO<br>PLAY</span><strong>${rows.filter(noPlay).length.toLocaleString("ja-JP")}</strong></div>`;document.querySelector("#medalSummary").innerHTML=medals;document.querySelector("#clearRateSummary").innerHTML=`<small>クリア率</small><strong>${rate}</strong>`;}
export function renderUsers(rows,page=1){const list=document.querySelector("#userList");if(!rows.length){list.innerHTML='<div class="empty">該当するユーザーがいません。</div>';return 1;}const field=document.querySelector("#userSortField")?.value||"username",direction=document.querySelector("#userSortOrder")?.value==="desc"?-1:1,sorted=[...rows].sort((a,b)=>{const result=field==="username"?String(a.username||"").localeCompare(String(b.username||""),"ja"):(Number(a[field])||0)-(Number(b[field])||0);return result*direction||String(a.username||"").localeCompare(String(b.username||""),"ja");}),pages=Math.ceil(sorted.length/PAGE_SIZE),current=Math.min(Math.max(1,Number(page)||1),pages),start=(current-1)*PAGE_SIZE;list.innerHTML=sorted.slice(start,start+PAGE_SIZE).map(x=>`<article class="user-row-v212"><strong class="user-name">${esc(x.username)}</strong><div class="user-metric-head"><span>最高クリア</span><span>ポックラ</span><span>ポプともID</span></div><div class="user-metric-values"><span>${x.highest_clear_level?`Lv.${x.highest_clear_level}`:"－"}</span><span>${x.pop_class==null?"－":Number(x.pop_class).toFixed(2)}</span><span class="poptomo-id">${x.poptomo_id?`<button class="poptomo-copy" type="button" data-copy-poptomo="${esc(x.poptomo_id)}" aria-label="ポプともID ${esc(x.poptomo_id)} をコピー">${esc(x.poptomo_id)}</button>`:"－"}</span></div></article>`).join("")+`<nav class="score-pager"><span>${sorted.length.toLocaleString("ja-JP")}人</span>${pager(current,pages,"user-page")}</nav>`;return current;}
export function showTab(name){document.querySelectorAll(".tab-panel").forEach(p=>p.hidden=p.id!==name+"Panel");document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));document.querySelector("#scoreOverview").hidden=name!=="scores";}
export function filterScores(rows){const q=document.querySelector("#searchInput").value.trim().toLowerCase(),level=document.querySelector("#levelFilter").value,version=document.querySelector("#versionFilter").value,medal=document.querySelector("#medalFilter").value,rankFilter=document.querySelector("#rankFilter").value,codes=MEDAL_GROUPS.find(([key])=>key===medal)?.[1]||[medal];return rows.filter(x=>{const unplayed=Number(x.score)<=0&&Number(x.version_score)<=0,currentRank=unplayed?"UNPLAYED":rankFromScore(x.score,x.medal_code);return`${x.genre} ${x.title} ${x.artist}`.toLowerCase().includes(q)&&(level==="ALL"||Number(x.level)===Number(level))&&(version==="ALL"||x.version_name===version)&&(medal==="ALL"||codes.includes(String(x.medal_code||"none").toLowerCase()))&&(rankFilter==="ALL"||currentRank===rankFilter);});}
