import{popClassSelection,rankFromScore,songPopClass}from"./scores.js?v=3.2.45";

const BASE="https://eacache.s.konaminet.jp/game/popn/popn29/images/p/";
const PAGE_SIZE=50;
export const MEDALS=[
 ["none","－　未プレー",""],
 ["perfect","PERFECT","perfect_00.png"],["fc_1_5","FC・GOOD 1～5","full_combo_00.png"],["fc_6_20","FC・GOOD 6～20","full_combo_01.png"],["fc_21_plus","FC・GOOD 21以上","full_combo_02.png"],["clear_bad_1_5","クリア・BAD 1～5","bad_00.png"],["clear_bad_6_20","クリア・BAD 6～20","bad_01.png"],
 ["clear_bad_21_plus","クリア・BAD 21以上","bad_02.png"],["long_off","ロングオフ","long_off.png"],["easy","EASYクリア","easy.png"],["failed_15_16","FAILED・15～16粒","groove_00.png"],["failed_12_14","FAILED・12～14粒","groove_01.png"],["failed_0_11","FAILED・11粒以下","groove_02.png"]
];
const CHART_SHORT={LIGHT:"LT",NORMAL:"NM",HYPER:"HP",EX:"EX"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function coolPerfectMedalHtml(extraClass=""){return `<img class="cool-perfect-medal${extraClass?` ${extraClass}`:""}" src="./assets/cool-perfect.png" alt="COOL PERFECT" title="COOL PERFECT">`;}

const MEDAL_ALIASES={a:"perfect",b:"fc_1_5",c:"fc_6_20",d:"fc_21_plus",e:"clear_bad_1_5",f:"clear_bad_6_20",g:"clear_bad_21_plus",k:"easy",h:"failed_15_16",l:"failed_15_16",i:"failed_12_14",m:"failed_12_14",j:"failed_0_11",n:"failed_0_11"};
export function medalInfo(code){const raw=String(code||"none").toLowerCase(),key=MEDAL_ALIASES[raw]||raw,logical=MEDALS.find(x=>x[0]===key);if(logical)return{label:logical[1],url:logical[2]?BASE+"howto/more/"+logical[2]:""};return{label:key.toUpperCase(),url:BASE+"common/medal/meda_big_"+key+".png"};}
export function setTheme(theme){const v=theme==="dark"?"dark":"light";document.documentElement.dataset.theme=v;const headerButton=document.querySelector("#themeButton");if(headerButton)headerButton.textContent=v==="light"?"☾":"☀";document.querySelector("#themeLabel").textContent=v==="light"?"ライト":"ダーク";localStorage.setItem("popn-theme",v);}
function pager(current,pages,attr){const options=Array.from({length:pages},(_,i)=>`<option value="${i+1}" ${i+1===current?"selected":""}>${i+1} / ${pages}</option>`).join("");return `<div class="pager-controls"><button type="button" data-${attr}="${current-1}" ${current===1?"disabled":""} aria-label="前のページ">◀</button><label class="pager-select"><select data-${attr}-select aria-label="ページを選択">${options}</select></label><button type="button" data-${attr}="${current+1}" ${current===pages?"disabled":""} aria-label="次のページ">▶</button></div>`;}
function scoreCard(row){const medal=medalInfo(row.medal_code),r=rankFromScore(row.score,row.medal_code),slug=r.replace("+","plus").toLowerCase(),noScore=Number(row.score)<=0&&Number(row.version_score)<=0,medalMissing=String(row.medal_code||"none").toLowerCase()==="none",medalHtml=Number(row.score)===100000?coolPerfectMedalHtml("card-cool-perfect"):medalMissing?'<span class="unplayed-mark">－</span>':medal.url?`<img src="${medal.url}" alt="${esc(medal.label)}" title="${esc(medal.label)}">`:`<span>${esc(medal.label)}</span>`,pc=songPopClass(row);return `<article class="score-card-v300">${row.banner_url?`<img class="song-banner" src="${esc(row.banner_url)}" alt="" loading="lazy">`:'<div class="song-banner banner-empty">NO IMAGE</div>'}<span class="card-medal">${medalHtml}</span>${noScore?'<span class="card-rank">－</span>':`<strong class="card-rank rank-text rank-${slug}">${r}</strong>`}<span class="card-score card-history"><small>歴代</small><strong>${Number(row.score)>0?Number(row.score):"－"}</strong></span><span class="card-score card-current"><small>今作</small><strong>${Number(row.version_score)>0?Number(row.version_score):"－"}</strong></span><span class="card-popclass"><small>PSR</small><strong>${pc.toFixed(2)}</strong></span><span class="card-chart ${row.chart.toLowerCase()}">${CHART_SHORT[row.chart]||esc(row.chart)}</span><span class="card-genre">${esc(row.genre)}</span><strong class="card-level">${row.level}</strong><h2 class="card-title">${esc(row.title)}</h2><button class="score-edit" type="button" data-edit-score="${row.id}">編集</button></article>`;}
export function renderScores(rows,page=1){const list=document.querySelector("#scoreList");if(!rows.length){list.innerHTML='<div class="empty">条件に合う曲がありません。</div>';return 1;}const chartOrder={EX:0,HYPER:1,NORMAL:2,LIGHT:3},field=document.querySelector("#scoreSortField")?.value||"level",direction=document.querySelector("#scoreSortOrder")?.value==="desc"?-1:1,medalOrder=code=>{const normalized=String(code||"none").toLowerCase(),index=MEDAL_GROUPS.findIndex(([,codes])=>codes.includes(normalized));return index<0?MEDAL_GROUPS.length:index;},wikiValue=row=>{const n=Number(row.wiki_difficulty_value);return Number.isFinite(n)?n:null;},fieldValue=(row,key)=>key==="medal"?(Number(row.score)===100000?-1:medalOrder(row.medal_code)):key==="current_medal"?medalOrder(row.current_medal_code):key==="pop_class"?songPopClass(row):key==="version"?Number(row.version_order??9999):key==="wiki_difficulty"?wikiValue(row):Number(row[key]||0),defaultDirection={level:-1,wiki_difficulty:-1,medal:1,current_medal:1,version_score:-1,score:-1,pop_class:-1,version:1},priority=["level","wiki_difficulty","medal","version_score","score","pop_class"],compareField=(a,b,key,dir=defaultDirection[key]??1)=>{const av=fieldValue(a,key),bv=fieldValue(b,key);if(key==="wiki_difficulty"){if(av==null&&bv==null)return 0;if(av==null)return 1;if(bv==null)return-1;}return(av-bv)*dir;},compare=(a,b)=>{let result=compareField(a,b,field,direction);if(result)return result;for(const key of priority){if(key===field)continue;result=compareField(a,b,key);if(result)return result;}return String(a.title||"").localeCompare(String(b.title||""),"ja")||(chartOrder[a.chart]??9)-(chartOrder[b.chart]??9);},sorted=[...rows].sort(compare),pages=Math.ceil(sorted.length/PAGE_SIZE),current=Math.min(Math.max(1,Number(page)||1),pages),start=(current-1)*PAGE_SIZE;list.innerHTML=sorted.slice(start,start+PAGE_SIZE).map(scoreCard).join("")+`<nav class="score-pager"><span>${sorted.length.toLocaleString("ja-JP")}件中 ${(start+1).toLocaleString("ja-JP")}～${Math.min(start+PAGE_SIZE,sorted.length).toLocaleString("ja-JP")}件</span>${pager(current,pages,"score-page")}</nav>`;return current;}
export function filterScores(rows){const q=document.querySelector("#searchInput").value.trim().toLowerCase(),level=document.querySelector("#levelFilter").value,version=document.querySelector("#versionFilter").value,medal=document.querySelector("#medalFilter").value,rankFilter=document.querySelector("#rankFilter").value,codes=MEDAL_GROUPS.find(([key])=>key===medal)?.[1]||[medal];return rows.filter(x=>{const unplayed=Number(x.score)<=0&&Number(x.version_score)<=0,currentRank=unplayed?"UNPLAYED":rankFromScore(x.score,x.medal_code),medalMatch=medal==="ALL"||(medal==="cool_perfect"?Number(x.score)===100000:codes.includes(String(x.medal_code||"none").toLowerCase()));return`${x.genre} ${x.title} ${x.artist}`.toLowerCase().includes(q)&&(level==="ALL"||Number(x.level)===Number(level))&&(version==="ALL"||x.version_name===version)&&medalMatch&&(rankFilter==="ALL"||currentRank===rankFilter);});}
