import{currentMedalCode,currentRankForRow,rankFromScore,popClassSelection,songPopClass}from"./scores.js?v=3.2.3";

const BASE="https://eacache.s.konaminet.jp/game/popn/popn29/images/p/";
const PAGE_SIZE=50;
export const MEDALS=[
 ["none","－　未プレー",""],
 ["perfect","PERFECT","perfect_00.png"],["fc_1_5","FC・GOOD 1～5","full_combo_00.png"],["fc_6_20","FC・GOOD 6～20","full_combo_01.png"],["fc_21_plus","FC・GOOD 21以上","full_combo_02.png"],["clear_bad_1_5","クリア・BAD 1～5","bad_00.png"],["clear_bad_6_20","クリア・BAD 6～20","bad_01.png"],
 ["clear_bad_21_plus","クリア・BAD 21以上","bad_02.png"],["long_off","ロングオフ","long_off.png"],["easy","EASYクリア","easy.png"],["failed_15_16","FAILED・15～16粒","groove_00.png"],["failed_12_14","FAILED・12～14粒","groove_01.png"],["failed_0_11","FAILED・11粒以下","groove_02.png"]
];
const CHART_SHORT={LIGHT:"LT",NORMAL:"NM",HYPER:"HP",EX:"EX"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function coolPerfectMedalHtml(extraClass=""){return `<img class="cool-perfect-medal${extraClass?` ${extraClass}`:""}" src="./assets/cool-perfect.png" alt="COOL PERFECT" title="COOL PERFECT">`;}

const MEDAL_ALIASES={a:"perfect",b:"fc_1_5",c:"fc_6_20",d:"fc_21_plus",e:"clear_bad_1_5",f:"clear_bad_6_20",g:"clear_bad_21_plus",k:"easy",h:"failed_15_16",l:"failed_15_16",i:"failed_12_14",m:"failed_12_14",j:"failed_0_11",n:"failed_0_11"};
export function medalInfo(code){const raw=String(code||"none").toLowerCase(),key=MEDAL_ALIASES[raw]||raw,logical=MEDALS.find(x=>x[0]===key);if(logical)return{label:logical[1],url:logical[2]?BASE+"howto/more/"+logical[2]:""};return{label:key.toUpperCase(),url:BASE+"common/medal/meda_big_"+key+".png"};}
export function setTheme(theme){const v=theme==="dark"?"dark":"light";document.documentElement.dataset.theme=v;const headerButton=document.querySelector("#themeButton");if(headerButton)headerButton.textContent=v==="light"?"☾":"☀";document.querySelector("#themeLabel").textContent=v==="light"?"ライト":"ダーク";localStorage.setItem("popn-theme",v);}
function pager(current,pages,attr){const options=Array.from({length:pages},(_,i)=>`<option value="${i+1}" ${i+1===current?"selected":""}>${i+1} / ${pages}</option>`).join("");return `<div class="pager-controls"><button type="button" data-${attr}="${current-1}" ${current===1?"disabled":""} aria-label="前のページ">◀</button><label class="pager-select"><select data-${attr}-select aria-label="ページを選択">${options}</select></label><button type="button" data-${attr}="${current+1}" ${current===pages?"disabled":""} aria-label="次のページ">▶</button></div>`;}
function scoreCard(row,useCurrentMedal=false){
 const historyMedal=medalInfo(row.medal_code),nowCode=currentMedalCode(row),nowMedal=medalInfo(nowCode);
 const historyScore=Number(row.score)||0,currentScore=Number(row.version_score)||0;
 const medalImage=(code,info,score)=>score===100000?coolPerfectMedalHtml("card-cool-perfect"):String(code||"none").toLowerCase()==="none"?'<span class="unplayed-mark">－</span>':info.url?`<img src="${esc(info.url)}" alt="${esc(info.label)}" loading="lazy">`:`<span>${esc(info.label)}</span>`;
 const rankImage=(score,code,label)=>{if(score<=0&&String(code||"none").toLowerCase()==="none")return '<span class="unplayed-mark">－</span>';const rank=rankFromScore(score,code),slug=rank.replace("+","plus").toLowerCase();return `<img src="./assets/ranks/${slug}.png" alt="${label} ${esc(rank)}" loading="lazy">`;};
 const record=(label,code,info,score)=>`<div class="score-record"><span class="score-record-label">${label}</span><span class="score-record-medal">${medalImage(code,info,score)}</span><span class="score-record-rank">${rankImage(score,code,label+"ランク")}</span><strong class="score-record-score">${score>0?score.toLocaleString("ja-JP"):"－"}</strong></div>`;
 return `<article class="score-card-v300 score-card-v312">
 <div class="score-card-upper">${row.banner_url?`<img class="song-banner" src="${esc(row.banner_url)}" alt="" loading="lazy">`:'<div class="song-banner banner-empty">NO IMAGE</div>'}
 <div class="score-records">${record("歴代",row.medal_code,historyMedal,historyScore)}${record("今作",nowCode,nowMedal,currentScore)}</div></div>
 <div class="score-card-lower"><span class="card-chart ${String(row.chart||"").toLowerCase()}">${CHART_SHORT[row.chart]||esc(row.chart)}</span><span class="card-genre">${esc(row.genre)}</span><span class="card-psr-label">PSR</span><button class="score-edit" type="button" data-edit-score="${esc(row.id)}">編集</button><strong class="card-level">${Number(row.level)||"－"}</strong><h2 class="card-title">${esc(row.title)}</h2><strong class="card-popclass">${songPopClass(row).toFixed(2)}</strong></div>
 </article>`;
}
export function renderScores(rows,page=1){const list=document.querySelector("#scoreList");if(!rows.length){list.innerHTML='<div class="empty">条件に合う曲がありません。</div>';return 1;}const chartOrder={EX:0,HYPER:1,NORMAL:2,LIGHT:3},field=document.querySelector("#scoreSortField")?.value||"medal",direction=document.querySelector("#scoreSortOrder")?.value==="desc"?-1:1,medalOrder=code=>{const normalized=String(code||"none").toLowerCase(),index=MEDAL_GROUPS.findIndex(([,codes])=>codes.includes(normalized));return index<0?MEDAL_GROUPS.length:index;},fieldValue=(row,key)=>key==="medal"?(Number(row.score)===100000?-1:medalOrder(row.medal_code)):key==="pop_class"?songPopClass(row):Number(row[key]||0),defaultDirection={level:-1,medal:1,version_score:-1,score:-1,pop_class:-1},priority=["level","medal","version_score","score","pop_class"],compareField=(a,b,key,dir=defaultDirection[key])=>(fieldValue(a,key)-fieldValue(b,key))*dir,compare=(a,b)=>{let result=compareField(a,b,field,direction);if(result)return result;for(const key of priority){if(key===field)continue;result=compareField(a,b,key);if(result)return result;}return String(a.title||"").localeCompare(String(b.title||""),"ja")||(chartOrder[a.chart]??9)-(chartOrder[b.chart]??9);},sorted=[...rows].sort(compare),pages=Math.ceil(sorted.length/PAGE_SIZE),current=Math.min(Math.max(1,Number(page)||1),pages),start=(current-1)*PAGE_SIZE;list.innerHTML=sorted.slice(start,start+PAGE_SIZE).map(scoreCard).join("")+`<nav class="score-pager"><span>${sorted.length.toLocaleString("ja-JP")}件中 ${(start+1).toLocaleString("ja-JP")}～${Math.min(start+PAGE_SIZE,sorted.length).toLocaleString("ja-JP")}件</span>${pager(current,pages,"score-page")}</nav>`;return current;}
export function renderPopClass(rows){const{current,other,total}=popClassSelection(rows),section=(title,items,limit)=>`<section class="popclass-group"><div class="popclass-group-title"><h2>${title}</h2><span>${items.length}/${limit}曲</span></div><div class="score-list">${items.length?items.map(item=>scoreCard(item,true)).join(""):'<div class="empty">対象曲がありません。</div>'}</div></section>`;document.querySelector("#totalPopClass").textContent=total.toFixed(2);document.querySelector("#popclassContent").innerHTML=section("新曲枠",current,20)+section("旧曲枠",other,40);return total;}
const MEDAL_GROUPS=[
 ["perfect",["perfect","a"]],["fc_1_5",["fc_1_5","b"]],["fc_6_20",["fc_6_20","c"]],["fc_21_plus",["fc_21_plus","d"]],
 ["clear_bad_1_5",["clear_bad_1_5","e"]],["clear_bad_6_20",["clear_bad_6_20","f"]],["clear_bad_21_plus",["clear_bad_21_plus","g"]],
 ["long_off",["long_off"]],["easy",["easy","k"]],["failed_15_16",["failed_15_16","h","l"]],["failed_12_14",["failed_12_14","i","m"]],["failed_0_11",["failed_0_11","j","n"]],["none",["none"]]
];
export function renderStats(rows){const code=x=>String(x.medal_code||"none").toLowerCase(),noPlay=x=>Number(x.score)<=0&&Number(x.version_score)<=0&&code(x)==="none",registered=rows.filter(x=>!noPlay(x)),unplayed=registered.filter(x=>code(x)==="none"),failed=x=>/^(h|i|j|l|m|n)$/.test(code(x))||code(x).startsWith("failed_"),clear=registered.filter(x=>code(x)!=="none"&&code(x)!=="easy"&&code(x)!=="k"&&code(x)!=="long_off"&&!failed(x)),rate=`${(clear.length/Math.max(1,registered.length)*100).toFixed(2)}%`,coolPerfect=registered.filter(x=>Number(x.score)===100000).length,groups=MEDAL_GROUPS.filter(([key])=>key!=="none"),counts=new Map(groups.map(([key,codes])=>[key,registered.filter(x=>codes.includes(code(x))&&(key!=="perfect"||Number(x.score)!==100000)).length])),coolPerfectHtml=`<div class="medal-stat cool-perfect-stat" title="COOL PERFECT">${coolPerfectMedalHtml()}<strong>${coolPerfect.toLocaleString("ja-JP")}</strong></div>`,medals=coolPerfectHtml+groups.map(([key])=>{const info=medalInfo(key);return `<div class="medal-stat" title="${esc(info.label)}"><img src="${info.url}" alt="${esc(info.label)}"><strong>${counts.get(key).toLocaleString("ja-JP")}</strong></div>`;}).join("")+`<div class="medal-stat unplayed-stat" title="未プレー"><span aria-label="未プレー">－</span><strong>${unplayed.length.toLocaleString("ja-JP")}</strong></div><div class="medal-stat no-play-stat"><span class="no-play-label">NO<br>PLAY</span><strong>${rows.filter(noPlay).length.toLocaleString("ja-JP")}</strong></div>`;document.querySelector("#medalSummary").innerHTML=medals;document.querySelector("#clearRateSummary").innerHTML=`<small>クリア率</small><strong>${rate}</strong>`;}
export function renderUsers(rows,page=1,rivalIds=new Set(),myId=null){const list=document.querySelector("#userList");if(!rows.length){list.innerHTML='<div class="empty">該当するユーザーがいません。</div>';return 1;}const field=document.querySelector("#userSortField")?.value||"pop_class",direction=(document.querySelector("#userSortOrder")?.value||"desc")==="desc"?-1:1,sorted=[...rows].sort((a,b)=>{const priority=["pop_class","official_popn_class","highest_clear_level","username"],compare=(key,dir)=>key==="username"?String(a.username||"").localeCompare(String(b.username||""),"ja")*dir:((Number(a[key])||0)-(Number(b[key])||0))*dir;let result=compare(field,direction);if(result)return result;for(const key of priority){if(key===field)continue;result=compare(key,key==="username"?1:-1);if(result)return result;}return String(a.user_id||"").localeCompare(String(b.user_id||""),"ja");}),pages=Math.ceil(sorted.length/PAGE_SIZE),current=Math.min(Math.max(1,Number(page)||1),pages),start=(current-1)*PAGE_SIZE;list.innerHTML=sorted.slice(start,start+PAGE_SIZE).map(x=>`<article class="user-row-v3095"><strong class="user-row-name">${esc(x.username)}</strong>${x.user_id!==myId?`<button type="button" class="rival-star ${rivalIds.has(x.user_id)?"is-active":""}" data-rival-id="${esc(x.user_id)}" aria-label="${rivalIds.has(x.user_id)?"ライバル解除":"ライバル登録"}" aria-pressed="${rivalIds.has(x.user_id)}">${rivalIds.has(x.user_id)?"★":"☆"}</button>`:""}<div class="user-row-metrics"><span class="user-row-metric"><small>最高クリア</small><strong>${x.highest_clear_level?`Lv.${x.highest_clear_level}`:"－"}</strong></span><span class="user-row-metric"><small>ポップンクラス</small><strong>${x.official_popn_class==null?"－":Number(x.official_popn_class).toFixed(2)}</strong></span><span class="user-row-metric"><small>PSR</small><strong>${x.pop_class==null?"－":Number(x.pop_class).toFixed(2)}</strong></span><span class="user-row-metric"><small>ポプともID</small><strong class="poptomo-id">${x.poptomo_id?`<button class="poptomo-copy" type="button" data-copy-poptomo="${esc(x.poptomo_id)}" aria-label="ポプともID ${esc(x.poptomo_id)} をコピー">${esc(x.poptomo_id)}</button>`:"－"}</strong></span></div></article>`).join("")+`<nav class="score-pager"><span>${sorted.length.toLocaleString("ja-JP")}人</span>${pager(current,pages,"user-page")}</nav>`;return current;}
export function showTab(name){document.querySelectorAll(".tab-panel").forEach(p=>p.hidden=p.id!==name+"Panel");document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));const overview=document.querySelector("#scoreOverview"),visible=name==="scores";overview.hidden=!visible;overview.style.display=visible?"":"none";}
export function filterScores(rows){const q=document.querySelector("#searchInput").value.trim().toLowerCase(),level=document.querySelector("#levelFilter").value,version=document.querySelector("#versionFilter").value,medal=document.querySelector("#medalFilter").value,rankFilter=document.querySelector("#rankFilter").value,codes=MEDAL_GROUPS.find(([key])=>key===medal)?.[1]||[medal];return rows.filter(x=>{const unplayed=Number(x.score)<=0&&Number(x.version_score)<=0,currentRank=unplayed?"UNPLAYED":currentRankForRow(x),medalMatch=medal==="ALL"||(medal==="cool_perfect"?Number(x.score)===100000:codes.includes(String(x.medal_code||"none").toLowerCase()));return`${x.genre} ${x.title} ${x.artist}`.toLowerCase().includes(q)&&(level==="ALL"||Number(x.level)===Number(level))&&(version==="ALL"||x.version_name===version)&&medalMatch&&(rankFilter==="ALL"||currentRank===rankFilter);});}
